-- バナナ品種データ 110件
-- けんゆー公開記事を優先し、ProMusa/PROSEA等の公開情報を補助して作成。
-- Supabase SQL Editorで part1 から順番に実行してください。

begin;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'ホーンプランテン', 'Horn Plantain', 'horn-plantain', '西アフリカ・中南米', 'ホーンプランテンは西アフリカ・中南米に関連する調理用タイプのバナナです。大きな果実で加熱向きの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '大型。草姿: 大型。', '大きな果実で加熱向き。', 'ほくほく', '穏やか', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '大型。家庭栽培での管理サイズ: 高。', '用途: 調理用。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。大株になりやすく、防風と十分な株間を確保したい。', '鉢では長期維持が難しいため、露地または大鉢で短期更新を前提にしたい。', '調理用品種として目的を決めて育てたい。完熟生食だけを期待すると印象が変わる。', 'ホーンプランテンは「調理用」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'マリコンゴ', 'Maricongo', 'maricongo', 'プエルトリコ', 'マリコンゴはプエルトリコに関連する調理用タイプのバナナです。プランテン系で揚げ物向きの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '大型。草姿: 大型。', 'プランテン系で揚げ物向き。', 'ほくほく', '穏やか', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '大型。家庭栽培での管理サイズ: 高。', '用途: 調理用。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。大株になりやすく、防風と十分な株間を確保したい。', '鉢では長期維持が難しいため、露地または大鉢で短期更新を前提にしたい。', '調理用品種として目的を決めて育てたい。完熟生食だけを期待すると印象が変わる。', 'マリコンゴは「調理用」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'ドワーフプエルトリカン', 'Dwarf Puerto Rican', 'dwarf-puerto-rican', 'プエルトリコ', 'ドワーフプエルトリカンはプエルトリコに関連する調理用タイプのバナナです。低めの株で調理用果を狙うの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '大型。草姿: 中型。', '低めの株で調理用果を狙う。', 'ほくほく', '穏やか', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '中型。家庭栽培での管理サイズ: 低。', '用途: 調理用。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。低めの株なので家庭菜園や鉢でも管理しやすい。', '鉢栽培でも検討しやすい。根詰まりと水切れに注意し、毎年の株分け候補を見ておく。', '調理用品種として目的を決めて育てたい。完熟生食だけを期待すると印象が変わる。', 'ドワーフプエルトリカンは「調理用」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'アフリカンライノホーン', 'African Rhino Horn', 'african-rhino-horn', 'アフリカ', 'アフリカンライノホーンはアフリカに関連する調理用タイプのバナナです。長い果実で加熱向きの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '非常に大型。草姿: 大型。', '長い果実で加熱向き。', 'ほくほく', '穏やか', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '大型。家庭栽培での管理サイズ: 高。', '用途: 調理用。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。大株になりやすく、防風と十分な株間を確保したい。', '鉢では長期維持が難しいため、露地または大鉢で短期更新を前提にしたい。', '調理用品種として目的を決めて育てたい。完熟生食だけを期待すると印象が変わる。', 'アフリカンライノホーンは「調理用」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'ネンドラン', 'Nendran', 'nendran', 'インド', 'ネンドランはインドに関連する調理・デザート兼用タイプのバナナです。加熱菓子やチップス向きの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '中ぶり。草姿: 中型。', '加熱菓子やチップス向き。', 'しっかり', '穏やか', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '中型。家庭栽培での管理サイズ: 中。', '用途: 調理・デザート兼用。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '調理用品種として目的を決めて育てたい。完熟生食だけを期待すると印象が変わる。', 'ネンドランは「調理・デザート兼用」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://plantuse.plantnet.org/en/Musa_(PROSEA_Fruits) / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'タンドック', 'Tanduk', 'tanduk', 'インドネシア', 'タンドックはインドネシアに関連する調理用タイプのバナナです。長い果実で加熱向きの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '大型。草姿: 大型。', '長い果実で加熱向き。', 'ほくほく', '穏やか', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '大型。家庭栽培での管理サイズ: 高。', '用途: 調理用。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。大株になりやすく、防風と十分な株間を確保したい。', '鉢では長期維持が難しいため、露地または大鉢で短期更新を前提にしたい。', '調理用品種として目的を決めて育てたい。完熟生食だけを期待すると印象が変わる。', 'タンドックは「調理用」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://plantuse.plantnet.org/en/Musa_(PROSEA_Fruits) / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'ピサンケポック', 'Pisang Kepok', 'pisang-kepok', 'インドネシア', 'ピサンケポックはインドネシアに関連する調理用タイプのバナナです。蒸し・揚げ物向きの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '太め。草姿: 大型。', '蒸し・揚げ物向き。', 'ほくほく', '穏やか', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '大型。家庭栽培での管理サイズ: 中。', '用途: 調理用。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '調理用品種として目的を決めて育てたい。完熟生食だけを期待すると印象が変わる。', 'ピサンケポックは「調理用」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://plantuse.plantnet.org/en/Musa_(PROSEA_Fruits) / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'ピサンアブ', 'Pisang Abu', 'pisang-abu', 'マレーシア', 'ピサンアブはマレーシアに関連する調理用タイプのバナナです。加熱で甘みが出るの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '太め。草姿: 大型。', '加熱で甘みが出る。', 'ほくほく', '穏やか', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '大型。家庭栽培での管理サイズ: 中。', '用途: 調理用。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '調理用品種として目的を決めて育てたい。完熟生食だけを期待すると印象が変わる。', 'ピサンアブは「調理用」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://plantuse.plantnet.org/en/Musa_(PROSEA_Fruits) / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'フアモア', 'Hua Moa', 'hua-moa', 'ポリネシア', 'フアモアはポリネシアに関連する調理・デザート兼用タイプのバナナです。完熟で甘く未熟果は調理向きの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '太め。草姿: 大型。', '完熟で甘く未熟果は調理向き。', 'しっかり', '穏やか', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '大型。家庭栽培での管理サイズ: 中。', '用途: 調理・デザート兼用。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '調理用品種として目的を決めて育てたい。完熟生食だけを期待すると印象が変わる。', 'フアモアは「調理・デザート兼用」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'ゴールドフィンガー', 'FHIA-01 Goldfinger', 'fhia-01-goldfinger', 'ホンジュラス育成', 'ゴールドフィンガーはホンジュラス育成に関連するデザートタイプのバナナです。甘酸っぱく病害に比較的強いの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '中ぶり。草姿: 中型。', '甘酸っぱく病害に比較的強い。', 'しっかり', 'フルーティー', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '中型。家庭栽培での管理サイズ: 中。', '用途: デザート。耐寒性目安: 強め。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。比較的作りやすい候補として試しやすい。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '家庭栽培では防風・肥培管理・収穫後の追熟を意識すると楽しみやすい。', 'ゴールドフィンガーは「デザート」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'モナリザ', 'FHIA-02 Mona Lisa', 'fhia-02-mona-lisa', 'ホンジュラス育成', 'モナリザはホンジュラス育成に関連するデザートタイプのバナナです。甘みがあり病害耐性を意識した系統の品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '中ぶり。草姿: 中型。', '甘みがあり病害耐性を意識した系統。', 'なめらか', '軽い', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '中型。家庭栽培での管理サイズ: 中。', '用途: デザート。耐寒性目安: 強め。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。比較的作りやすい候補として試しやすい。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '家庭栽培では防風・肥培管理・収穫後の追熟を意識すると楽しみやすい。', 'モナリザは「デザート」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'スイートハート', 'FHIA-03 Sweetheart', 'fhia-03-sweetheart', 'ホンジュラス育成', 'スイートハートはホンジュラス育成に関連するデザート・調理兼用タイプのバナナです。甘みと耐病性のバランス型の品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '中ぶり。草姿: 中型。', '甘みと耐病性のバランス型。', 'しっかり', '軽い', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '中型。家庭栽培での管理サイズ: 中。', '用途: デザート・調理兼用。耐寒性目安: 強め。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。比較的作りやすい候補として試しやすい。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '調理用品種として目的を決めて育てたい。完熟生食だけを期待すると印象が変わる。', 'スイートハートは「デザート・調理兼用」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'FHIA-17', 'FHIA-17', 'fhia-17', 'ホンジュラス育成', 'FHIA-17はホンジュラス育成に関連するデザートタイプのバナナです。甘みがあり耐病性を狙った品種の品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '中ぶり。草姿: 大型。', '甘みがあり耐病性を狙った品種。', 'なめらか', '軽い', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '大型。家庭栽培での管理サイズ: 中。', '用途: デザート。耐寒性目安: 強め。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。比較的作りやすい候補として試しやすい。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '家庭栽培では防風・肥培管理・収穫後の追熟を意識すると楽しみやすい。', 'FHIA-17は「デザート」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'FHIA-18', 'FHIA-18', 'fhia-18', 'ホンジュラス育成', 'FHIA-18はホンジュラス育成に関連するデザートタイプのバナナです。甘酸っぱく家庭向きの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '中ぶり。草姿: 中型。', '甘酸っぱく家庭向き。', 'なめらか', '軽い芳香', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '中型。家庭栽培での管理サイズ: 中。', '用途: デザート。耐寒性目安: 強め。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。比較的作りやすい候補として試しやすい。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '家庭栽培では防風・肥培管理・収穫後の追熟を意識すると楽しみやすい。', 'FHIA-18は「デザート」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'ヤンガンビKm5', 'Yangambi Km5', 'yangambi-km5', 'コンゴ民主共和国', 'ヤンガンビKm5はコンゴ民主共和国に関連するデザートタイプのバナナです。甘みがあり耐病性で知られるの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '小ぶり。草姿: 中型。', '甘みがあり耐病性で知られる。', 'なめらか', '軽い', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '中型。家庭栽培での管理サイズ: 中。', '用途: デザート。耐寒性目安: 強め。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。比較的作りやすい候補として試しやすい。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '家庭栽培では防風・肥培管理・収穫後の追熟を意識すると楽しみやすい。', 'ヤンガンビKm5は「デザート」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'ローズバナナ', 'Rose', 'rose', '東南アジア', 'ローズバナナは東南アジアに関連するデザートタイプのバナナです。香りのよい甘さの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '小ぶり。草姿: 小型。', '香りのよい甘さ。', 'なめらか', '芳香', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '小型。家庭栽培での管理サイズ: 低。', '用途: デザート。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。低めの株なので家庭菜園や鉢でも管理しやすい。', '鉢栽培でも検討しやすい。根詰まりと水切れに注意し、毎年の株分け候補を見ておく。', '家庭栽培では防風・肥培管理・収穫後の追熟を意識すると楽しみやすい。', 'ローズバナナは「デザート」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'レッドバナナ', 'Red banana', 'red-banana', '東南アジア・中南米', 'レッドバナナは東南アジア・中南米に関連するデザートタイプのバナナです。濃い甘みと独特の香りの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '中ぶり。草姿: 中型。', '濃い甘みと独特の香り。', 'ねっとり', '芳香', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '中型。家庭栽培での管理サイズ: 中。', '用途: デザート。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '家庭栽培では防風・肥培管理・収穫後の追熟を意識すると楽しみやすい。', 'レッドバナナは「デザート」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'ドワーフレッド', 'Dwarf Red', 'dwarf-red', 'レッド系', 'ドワーフレッドはレッド系に関連するデザートタイプのバナナです。赤皮系の濃い甘みの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '中ぶり。草姿: 小型。', '赤皮系の濃い甘み。', 'ねっとり', '芳香', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '小型。家庭栽培での管理サイズ: 低。', '用途: デザート。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。低めの株なので家庭菜園や鉢でも管理しやすい。', '鉢栽培でも検討しやすい。根詰まりと水切れに注意し、毎年の株分け候補を見ておく。', '家庭栽培では防風・肥培管理・収穫後の追熟を意識すると楽しみやすい。', 'ドワーフレッドは「デザート」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'モラード', 'Morado', 'morado', 'レッド系', 'モラードはレッド系に関連するデザートタイプのバナナです。濃厚で香りがあるの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '中ぶり。草姿: 中型。', '濃厚で香りがある。', 'ねっとり', '芳香', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '中型。家庭栽培での管理サイズ: 中。', '用途: デザート。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '家庭栽培では防風・肥培管理・収穫後の追熟を意識すると楽しみやすい。', 'モラードは「デザート」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'グリーンレッド', 'Green Red', 'green-red', 'レッド系', 'グリーンレッドはレッド系に関連するデザートタイプのバナナです。甘みが濃く個性的の品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '中ぶり。草姿: 中型。', '甘みが濃く個性的。', 'ねっとり', '芳香', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '中型。家庭栽培での管理サイズ: 中。', '用途: デザート。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '家庭栽培では防風・肥培管理・収穫後の追熟を意識すると楽しみやすい。', 'グリーンレッドは「デザート」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'ピサンジャリブアヤ', 'Pisang Jari Buaya', 'pisang-jari-buaya', 'インドネシア', 'ピサンジャリブアヤはインドネシアに関連するデザートタイプのバナナです。小型で甘いの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '細め。草姿: 小型。', '小型で甘い。', 'なめらか', '軽い', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '小型。家庭栽培での管理サイズ: 低。', '用途: デザート。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。低めの株なので家庭菜園や鉢でも管理しやすい。', '鉢栽培でも検討しやすい。根詰まりと水切れに注意し、毎年の株分け候補を見ておく。', '家庭栽培では防風・肥培管理・収穫後の追熟を意識すると楽しみやすい。', 'ピサンジャリブアヤは「デザート」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'ピサンケリング', 'Pisang Keling', 'pisang-keling', '東南アジア', 'ピサンケリングは東南アジアに関連するデザートタイプのバナナです。甘みと香りがあるの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '小ぶり。草姿: 中型。', '甘みと香りがある。', 'やや締まる', '芳香', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '中型。家庭栽培での管理サイズ: 中。', '用途: デザート。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '家庭栽培では防風・肥培管理・収穫後の追熟を意識すると楽しみやすい。', 'ピサンケリングは「デザート」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://plantuse.plantnet.org/en/Musa_(PROSEA_Fruits) / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'カラプア', 'Kalapua', 'kalapua', '太平洋諸島', 'カラプアは太平洋諸島に関連する調理・デザート兼用タイプのバナナです。地域利用の幅が広いの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '中ぶり。草姿: 中型。', '地域利用の幅が広い。', 'しっかり', '穏やか', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '中型。家庭栽培での管理サイズ: 中。', '用途: 調理・デザート兼用。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '調理用品種として目的を決めて育てたい。完熟生食だけを期待すると印象が変わる。', 'カラプアは「調理・デザート兼用」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Pisang+Awak / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'マンザナ', 'Manzana', 'manzana', '中南米', 'マンザナは中南米に関連するデザートタイプのバナナです。甘酸っぱいりんご風味の品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '小ぶり。草姿: 中型。', '甘酸っぱいりんご風味。', 'やや締まる', 'フルーティー', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '中型。家庭栽培での管理サイズ: 中。', '用途: デザート。耐寒性目安: 普通。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '家庭栽培では防風・肥培管理・収穫後の追熟を意識すると楽しみやすい。', 'マンザナは「デザート」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://plantuse.plantnet.org/en/Musa_(PROSEA_Fruits) / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;

insert into public.cultivars (fruit_id, name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, tree_vigor, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, private_notes, is_public, is_for_sale) values ((select id from public.fruits where slug = 'banana'), 'テキサススター', 'Texas Star', 'texas-star', 'アメリカ', 'テキサススターはアメリカに関連するデザートタイプのバナナです。家庭栽培向きの甘さの品種として、家庭栽培では株の大きさ、風対策、病害への注意を見ながら比較したい品種です。', '中ぶり。草姿: 中型。', '家庭栽培向きの甘さ。', 'なめらか', '軽い', '沖縄では加温なしでも周年的に生育しやすいが、収穫時期は植え付け時期・株の充実・冬越し条件で変動。', '中型。家庭栽培での管理サイズ: 中。', '用途: デザート。耐寒性目安: 強め。バナナセセリ、バンチートップ、パナマ病、台風による倒伏に注意。', '沖縄では露地・庭植えの候補になりますが、台風対策、排水、株元の保護が重要です。比較的作りやすい候補として試しやすい。', '大鉢なら試せるが、肥料切れと乾燥で果実品質が落ちやすい。', '家庭栽培では防風・肥培管理・収穫後の追熟を意識すると楽しみやすい。', 'テキサススターは「デザート」として見比べたい品種。沖縄では味だけでなく、株の大きさ、風への強さ、収穫後の追熟まで含めて評価したいです。', null, 'https://www.promusa.org/Diversity+of+banana+cultivars+portal / 補助: https://www.promusa.org/Diversity+of+banana+cultivars+portal', true, false) on conflict (fruit_id, slug) do nothing;


commit;
