-- Coffee Varieties Catalog を参考に，コーヒー果樹ページと主要品種を追加・更新します。
-- 出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.

begin;

insert into public.fruits (
  name_ja,
  name_en,
  slug,
  scientific_name,
  family_name,
  origin,
  description,
  growth_habit,
  flower_description,
  fruit_description,
  cultivation_summary,
  okinawa_suitability,
  public_notes,
  private_notes,
  is_public,
  display_order
) values (
  'コーヒー',
  'Coffee',
  'coffee',
  'Coffea arabica / Coffea canephora',
  'アカネ科',
  'エチオピア，熱帯アフリカ',
  'コーヒーは果実の中にできる種子を精製・乾燥・焙煎して利用する熱帯果樹です．主にアラビカ種とカネフォラ種（ロブスタ）が栽培され，品種によって樹姿，豆の大きさ，収量，病害抵抗性，カップ品質の傾向が大きく異なります．',
  '常緑性の低木から小高木です．アラビカは比較的冷涼な高地で品質が出やすく，ロブスタは高温多湿条件への適応や多収性を評価しやすい傾向があります．',
  '白色で香りのある花を節部にまとめて咲かせます．降雨や灌水後に一斉開花しやすく，開花時期の記録は収穫時期の予測にも役立ちます．',
  '赤または黄色に熟すコーヒーチェリーを収穫し，果肉を除いた種子をコーヒー豆として利用します．品種によって豆サイズ，熟期，チェリーから生豆への歩留まりが変わります．',
  '半日陰，防風，排水性，乾湿のリズム，収穫後の精製方法を合わせて記録したい作物です．沖縄では高温多湿と台風を前提に，樹姿の管理，病害虫，果実の成熟揃い，カップ品質を比較すると図鑑として価値が出ます．',
  '沖縄では露地越冬しやすい場所もありますが，強風，塩害，夏の直射，排水不良に注意します．アラビカの高標高品質を平地でそのまま再現するのは難しい可能性があるため，品種ごとの樹勢，収量，精製後の風味を園地条件で比較したい果樹です．',
  '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04. 糸満フルーツ園けんちゃん 果樹図鑑の栽培記録で今後補正予定．',
  'ユーザー提供PDF Coffee Varieties Catalog.pdf を参照して初期登録．',
  true,
  coalesce((select display_order from public.fruits where slug = 'coffee'), 1550)
)
on conflict (slug) do update set
  name_ja = excluded.name_ja,
  name_en = excluded.name_en,
  scientific_name = excluded.scientific_name,
  family_name = excluded.family_name,
  origin = excluded.origin,
  description = excluded.description,
  growth_habit = excluded.growth_habit,
  flower_description = excluded.flower_description,
  fruit_description = excluded.fruit_description,
  cultivation_summary = excluded.cultivation_summary,
  okinawa_suitability = excluded.okinawa_suitability,
  public_notes = excluded.public_notes,
  private_notes = excluded.private_notes,
  is_public = true,
  display_order = coalesce(public.fruits.display_order, excluded.display_order),
  updated_at = now();

with coffee as (
  select id from public.fruits where slug = 'coffee'
), new_cultivars as (
  select *
  from (values
    (
      'ティピカ', 'Typica', 'typica', 'エチオピア由来，世界各地へ伝播',
      'アラビカの基本品種群の一つです．高性で収量は高くありませんが，高標高では上品で透明感のある品質を出しやすい系統として，多くの品種の親になっています．',
      '豆サイズ: 大．', '高標高でVery Good評価．繊細で伝統的なアラビカ品質を見たい品種．', '透明感が出やすい', '穏やか', '平均',
      'アラビカ / Bourbon-Typica group，Typica related', '高性', '低い',
      '高性で樹が大きく，単幹仕立てなら3000-4000本/ha程度が目安とされます．',
      'さび病，線虫，コーヒーベリー病に弱いとされ，病害管理が重要です．',
      '沖縄では品質比較用の基準品種として面白い一方，台風と病害を受けやすいため防風と剪定管理を強めたいです．',
      '鉢では樹高を抑えながら観察向きです．長期的な収量より，開花と少量収穫の記録向きです．',
      '病害に弱いため，初めてなら管理しやすい矮性・耐病性品種と比較して育てたいです．',
      'コーヒー品種を見る基準として入れておきたい古典品種です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: tall，large bean，low yield，Very Good high-altitude quality，susceptible to rust/nematode/CBD．', true, false
    ),
    (
      'ブルボン', 'Bourbon', 'bourbon', 'インド洋地域から世界各地へ伝播',
      '世界的に重要なアラビカ古典品種です．高性で収量は中程度，高標高ではVery Good評価のカップ品質が期待されます．Caturra，Villa Sarchi，Pacasなど多くの矮性突然変異や派生品種の基礎になっています．',
      '豆サイズ: 平均．', '高標高でVery Good評価．甘さとまとまりを比較したい品種．', 'なめらか', '穏やか', '早い',
      'アラビカ / Bourbon-Typica group，Bourbon related', '高性', '中',
      '高性で，初収穫は4年目目安とされます．',
      'さび病，線虫，コーヒーベリー病に弱いとされます．',
      '沖縄では品種の基準として価値がありますが，耐病性より品質比較を目的にしたい品種です．風の当たりにくい場所で育てたいです．',
      '鉢では樹高管理が必要です．枝を作りすぎず，収穫量より観察を優先すると扱いやすいです．',
      '病害抵抗性品種ではないため，初心者は栽培環境を整えてから試したいです．',
      '古典品種の味の基準として残したい品種です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: tall，average bean，medium yield，Very Good high-altitude quality，early ripening．', true, false
    ),
    (
      'カトゥーラ', 'Caturra', 'caturra', 'ブラジル',
      'ブルボンの自然突然変異から選抜された矮性品種です．コンパクトで密植しやすく，標準的な品質と中程度の収量が期待できますが，さび病には弱い品種です．',
      '豆サイズ: 平均．', '高標高でGood評価．標準的で比較しやすい品質．', 'バランス型', '穏やか', '平均',
      'アラビカ / Bourbon-Typica group，Bourbon related', '矮性', '中',
      '矮性・コンパクトで，単幹仕立てなら5000-6000本/ha程度の密植が可能とされます．',
      'さび病，線虫，コーヒーベリー病に弱く，肥培要求は高めです．',
      '沖縄ではコンパクトさが利点です．病害の出方と夏場の樹勢，果実の成熟揃いを記録したいです．',
      '鉢向きです．樹形を小さく保ちやすく，家庭での開花・結実観察に使いやすいです．',
      '樹は扱いやすいですが，病害に弱い点は注意です．',
      '鉢や小スペースでコーヒーを比較するなら候補にしやすい品種です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: dwarf/compact，average bean，medium yield，Good high-altitude quality，rust susceptible．', true, false
    ),
    (
      'カトゥアイ', 'Catuai', 'catuai', 'ブラジル',
      'Mundo NovoとCaturraの交配から作られたコンパクトな品種です．中程度の収量とGood評価の品質があり，中央アメリカで広く比較されてきました．さび病に弱い点は重要です．',
      '豆サイズ: 平均．', '高標高でGood評価．標準的で使いやすい風味．', 'バランス型', '穏やか', '平均',
      'アラビカ / Bourbon-Typica group，Typica and Bourbon related', '矮性', '中',
      '矮性・コンパクトで密植向きです．',
      'さび病，線虫，コーヒーベリー病に弱く，肥培要求は高いとされます．',
      '沖縄では鉢や小面積での比較に向きます．病害と強光による葉傷みを見ながら評価したいです．',
      '鉢栽培の候補です．枝数と着果量を調整しやすいタイプです．',
      '栽培はしやすい形ですが，病害管理を前提にしたいです．',
      'Caturraとの違いを見比べると楽しい品種です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: Mundo Novo x Caturra，dwarf/compact，medium yield，Good quality，rust susceptible．', true, false
    ),
    (
      'ムンドノーボ', 'Mundo Novo', 'mundo-novo', 'ブラジル',
      'Typica系とBourbon系の背景を持つ高性品種です．樹勢と収量のバランスがよく，ブラジルの重要品種としてCatuaiなどの親にもなっています．',
      '豆サイズ: 平均から大．', '高標高でGood評価．クラシックなアラビカ品質．', 'バランス型', '穏やか', '平均',
      'アラビカ / Bourbon-Typica group', '高性', '中から高い',
      '高性で樹勢が強く，広めの株間と剪定管理が必要です．',
      'さび病には強くないため，湿度の高い園地では観察が必要です．',
      '沖縄では樹が大きくなりやすい点を活かしつつ，台風前提の低め管理にしたい品種です．',
      '鉢では長期維持より若木の観察向きです．',
      'スペースがある人向けです．',
      'Catuaiの親として系譜面でも重要です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのBourbon-Typica系統情報をもとに要約．', true, false
    ),
    (
      'ゲイシャ（パナマ）', 'Geisha (Panama)', 'geisha-panama', 'エチオピア由来，パナマで有名化',
      'エチオピア系ランドレース由来の高品質品種です．高標高で非常に個性的な香味を示すことで知られ，スペシャルティコーヒーの代表的品種として扱われます．',
      '豆サイズ: 大．', '高標高でExceptional評価．華やかで複雑な香味を比較したい品種．', '繊細', 'フローラル傾向', '平均',
      'アラビカ / Ethiopian landrace', '高性', '低いから中',
      '高性で，品質重視の管理に向きます．',
      '病害抵抗性より品質評価を優先する品種です．園地条件で結果が大きく変わります．',
      '沖縄平地では本来の高標高品質を再現しにくい可能性があります．それでも香り，熟期，精製後の違いを記録する価値が高い品種です．',
      '鉢では収量より観察向きです．強光と乾燥を避けて育てたいです．',
      '品質評価を目的にする中上級者向きです．',
      '図鑑には必ず入れておきたい世界的な注目品種です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: Ethiopian landrace，high cup quality potential．', true, false
    ),
    (
      'パカマラ', 'Pacamara', 'pacamara', 'エルサルバドル',
      'PacasとMaragogipeの交配に由来する大粒系品種です．大きな豆と独特の品質で知られますが，栽培地や管理によって品質差が出やすいタイプです．',
      '豆サイズ: 非常に大．', '高標高でVery Goodから個性的な品質を狙える品種．', '厚みが出やすい', '個性的', '平均',
      'アラビカ / Bourbon-Typica group', '高性から中間', '中',
      '大粒で樹勢を確保したい品種です．',
      '病害への強さを目的にした品種ではなく，栽培条件の影響を受けやすいです．',
      '沖縄では大粒豆の出方，成熟揃い，精製後の個性を比較したいです．風害対策を強めたい品種です．',
      '鉢では実付きと豆の充実を安定させにくいため，大鉢で控えめに管理したいです．',
      '大粒系を楽しみたい人向けです．',
      'マラゴジッペ系の大粒性を見る品種として面白いです．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのPacamara系統情報をもとに要約．', true, false
    ),
    (
      'マラゴジッペ', 'Maragogipe', 'maragogipe', 'ブラジル',
      'Typicaの自然突然変異に由来する非常に大粒の品種です．葉や節間も大きく，収量は低い一方，中央アメリカではGoodからVery Goodの品質が評価されます．',
      '豆サイズ: 非常に大．', '高標高でVery Good評価．大粒豆の個性を楽しむ品種．', 'やわらかい印象', '穏やか', '平均',
      'アラビカ / Bourbon-Typica group，Typica related', '高性', '低い',
      '葉と節間が大きく，樹も大きくなります．',
      'さび病，線虫，コーヒーベリー病に弱く，生産性は低いとされます．',
      '沖縄では収量目的より，大粒豆と樹姿の観察向きです．台風時に枝葉が傷みやすい可能性があります．',
      '鉢では大きくなりやすいため，観賞・少量収穫向きです．',
      '収量を期待する初心者向きではありません．',
      '大粒豆の代表として図鑑に残したい品種です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: natural mutation of Typica，very large bean，low yield，rust/nematode/CBD susceptible．', true, false
    ),
    (
      'SL28', 'SL28', 'sl28', 'ケニア',
      'ケニアを代表する高品質品種です．収量は低いものの，高標高でExceptional評価のカップ品質を示し，乾燥耐性も知られます．病害には弱いため，品質重視の比較品種です．',
      '豆サイズ: 大．', '高標高でExceptional評価．明るい酸と複雑さを比較したい品種．', '繊細', '華やか', '不明',
      'アラビカ / Bourbon-Typica group，Bourbon related', '高性', '低い',
      '高性で，枝が収穫後に下がりやすい傾向があります．',
      'さび病，線虫，コーヒーベリー病に弱い一方，乾燥耐性があります．',
      '沖縄では高品質系として記録したい品種です．病害管理と強風対策を前提に，少量でも精製して評価したいです．',
      '鉢では樹姿が大きくなりやすく，収量より観察向きです．',
      '病害に弱く，中上級者向きです．',
      'カップ品質の比較軸として重要な品種です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: large bean，low yield，Exceptional high-altitude quality，drought tolerant，susceptible to major diseases．', true, false
    ),
    (
      'SL34', 'SL34', 'sl34', 'ケニア',
      'ケニア系の高品質品種です．高標高でExceptional評価の品質を示し，雨量のある高地に適応します．コーヒーベリー病などには弱く，品質重視で扱いたい品種です．',
      '豆サイズ: 大．', '高標高でExceptional評価．奥行きのある品質を比較したい品種．', 'なめらか', '華やか', '不明',
      'アラビカ / Bourbon-Typica group，Typica related', '高性', '中',
      '高性で，側枝は年数とともに下がりやすい傾向があります．',
      'さび病，線虫，コーヒーベリー病に弱いとされます．',
      '沖縄では高温多湿下での病害発生を慎重に見たい品種です．品質比較用として価値があります．',
      '鉢では樹高管理をしながら少量収穫を狙うタイプです．',
      '品質を見たい中上級者向きです．',
      'SL28と並べて比較すると面白い品種です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: large bean，medium yield，Exceptional quality，adapted to high altitude with good rainfall．', true, false
    ),
    (
      'ジャバ', 'Java', 'java', 'エチオピア由来，インドネシア・中央アメリカで栽培',
      'エチオピア系の背景を持つ品種で，細長い豆と良好な品質が特徴です．地域によって呼び名や選抜系統に幅があり，品質比較用として重要です．',
      '豆サイズ: 大．', '高標高でGoodからVery Good評価を期待．', 'すっきり', '穏やか', '平均',
      'アラビカ / Ethiopian landrace related', '高性', '中',
      '高性で，樹形を作りながら栽培します．',
      '病害抵抗性は系統や地域で差が出やすいため，園地で確認が必要です．',
      '沖縄では香味と樹勢のバランスを見たい品種です．強風で枝が傷まないよう低めに作りたいです．',
      '鉢では樹高調整が必要ですが，若木の観察には向きます．',
      '比較栽培向きです．',
      'ゲイシャとは別系統のエチオピア由来品種として入れておきたいです．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのJava品種情報をもとに要約．', true, false
    ),
    (
      'バティアン', 'Batian', 'batian', 'ケニア',
      'SL28，SL34，Rume Sudan，N39，K7，Timor Hybridなどを背景に持つケニアの複合品種です．高収量，さび病耐性，コーヒーベリー病抵抗性，Very Good評価の品質を組み合わせます．',
      '豆サイズ: 非常に大．', '高標高でVery Good評価．耐病性と品質を両立しやすい品種．', 'しっかり', '穏やか', '不明',
      'アラビカ / Introgressed，Other', '高性', '高い',
      '高性ですが，小規模栽培でも扱いやすい耐性と樹勢が評価されています．',
      'さび病は中間抵抗性，コーヒーベリー病は抵抗性，線虫には弱いとされます．',
      '沖縄では耐病性と樹勢の両面から試す価値があります．高性なので台風対策を組み込んで評価したいです．',
      '鉢では大きくなりやすいため，大鉢か露地向きです．',
      '耐病性があり比較的試しやすい候補です．',
      '品質と耐病性を両方見たい時の有力候補です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: composite parentage，tall，very large bean，high yield，Very Good quality，CBD resistant．', true, false
    ),
    (
      'ルイル11', 'Ruiru 11', 'ruiru-11', 'ケニア',
      'ケニアで育成された矮性・コンパクトなハイブリッドです．高収量で，さび病に高い抵抗性，コーヒーベリー病に抵抗性を示します．品質はGood評価で，栽培性を重視したい品種です．',
      '豆サイズ: 大．', '高標高でGood評価．耐病性を含めた総合力を見る品種．', 'バランス型', '穏やか', '平均',
      'アラビカ / F1 hybrid，introgressed', '矮性', '非常に高い',
      '矮性・コンパクトで，複数幹仕立て2000-3000本/ha程度が目安とされます．',
      'さび病に高抵抗性，コーヒーベリー病に抵抗性，線虫には弱いとされます．',
      '沖縄では病害抵抗性とコンパクトさが魅力です．精製品質と樹勢を合わせて比較したい品種です．',
      '鉢でも試しやすい候補です．枝数を管理すれば観察しやすいです．',
      '耐病性重視なら試しやすいです．',
      'ケニア系の実用品種として価値があります．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: dwarf/compact，large bean，very high yield，high rust resistance，CBD resistant．', true, false
    ),
    (
      'S795', 'S795', 's795', 'インド',
      'インドで広く知られるアラビカ品種です．品質と収量のバランスを目的に使われ，地域によってはさび病への一定の耐性が評価されてきました．',
      '豆サイズ: 平均から大．', 'Good評価を期待する実用品種．', 'バランス型', '穏やか', '平均',
      'アラビカ / Introgressed，S.288系背景', '高性', '中',
      '高性で，樹勢を維持しながら栽培します．',
      'さび病への反応は地域の病原菌レースで変わるため，現地観察が必要です．',
      '沖縄では高温多湿での葉の健全性と収量を見たい品種です．',
      '鉢では樹高管理が必要です．',
      '比較栽培向きです．',
      'インド系アラビカの代表として登録しておきたいです．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのS795品種情報をもとに要約．', true, false
    ),
    (
      'アナカフェ14', 'Anacafe 14', 'anacafe-14', 'グアテマラ',
      'Timor Hybrid 832/1 x CaturraにPacamaraを戻した背景を持つCatimor関連品種です．非常に大粒で高収量，1300m以上でGood評価の品質が期待されます．ただし品種の均一性には注意が必要です．',
      '豆サイズ: 非常に大．', '1300m以上でGood評価．大粒と多収性を見る品種．', 'しっかり', '穏やか', '遅い',
      'アラビカ / Introgressed，Catimor related', '矮性', '高い',
      '矮性・コンパクトで初収穫は2年目目安，肥培要求は高めです．',
      'さび病は中間抵抗性，線虫とコーヒーベリー病には弱いとされます．乾燥耐性があります．',
      '沖縄では大粒性と多収性を試す価値があります．品種のばらつきが出る可能性があるため，株ごとの記録を残したいです．',
      '鉢でも試せますが，肥料切れを避けたい品種です．',
      '多収性を見たい人向きです．',
      '大粒でわかりやすい特徴がある品種です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: dwarf/compact，very large bean，high yield，late ripening，drought tolerant，not uniform．', true, false
    ),
    (
      'コスタリカ95', 'Costa Rica 95', 'costa-rica-95', 'コスタリカ',
      'Timor Hybrid 832/1 x Caturraに由来するCatimor関連品種です．暖かい地域や酸性土壌に適応し，高収量ですが，高標高品質はLow評価です．近年は地域によってさび病感受性が確認されています．',
      '豆サイズ: 平均．', '高標高でLow評価．収量と環境適応を重視する品種．', '実用品質', '穏やか', '平均',
      'アラビカ / Introgressed，Catimor related', '矮性', '高い',
      '矮性・コンパクトで密植向き，肥培要求は高めです．',
      'さび病，線虫，コーヒーベリー病に弱い評価があり，Ojo de Galloにも注意が必要とされます．',
      '沖縄では暖地適応の観察対象になります．品質より樹勢，着果，病害の出方を比較したい品種です．',
      '鉢でも管理しやすい樹形ですが，肥培を切らさないようにしたいです．',
      '収量比較向きです．',
      '暖かい地域向けの比較品種として残したいです．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: adapted to warm zones and acidic soils，high yield，low quality，rust susceptibility noted in Costa Rica．', true, false
    ),
    (
      'パライネマ', 'Parainema', 'parainema', 'ホンジュラス',
      'Sarchimor系の耐病性品種です．線虫抵抗性やさび病抵抗性を重視して選ばれることがあり，低地から中標高での実用性を見たい品種です．',
      '豆サイズ: 大．', '高標高でGood評価を期待．耐病性と品質のバランスを見る品種．', 'しっかり', '穏やか', '平均',
      'アラビカ / Introgressed，Sarchimor related', '矮性', '高い',
      '矮性・コンパクトで栽培密度を上げやすい品種です．',
      'さび病や線虫への抵抗性を評価したい品種です．',
      '沖縄では根の健全性や高温多湿期の葉の状態を見たい候補です．耐病性重視の比較に向きます．',
      '鉢でも試しやすいです．',
      '耐病性重視なら候補です．',
      '家庭栽培でも実用面の比較に使いやすそうです．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのParainema品種情報をもとに要約．', true, false
    ),
    (
      'マルセレサ', 'Marsellesa', 'marsellesa', 'ニカラグア・中央アメリカ',
      'Sarchimor系の実用品種で，収量と耐病性を重視して選ばれます．標準的な品質と栽培安定性を比較したい品種です．',
      '豆サイズ: 平均から大．', 'Good評価を期待する実用品種．', 'バランス型', '穏やか', '平均',
      'アラビカ / Introgressed，Sarchimor related', '矮性', '高い',
      'コンパクトで管理しやすいタイプです．',
      'さび病抵抗性を目的に比較したい品種です．',
      '沖縄では耐病性と収量を見たい実用候補です．強風後の回復も記録したいです．',
      '鉢でも候補になります．',
      '実用性重視で試しやすいです．',
      '品質重視品種と並べて育てると違いが分かりやすいです．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのMarsellesa品種情報をもとに要約．', true, false
    ),
    (
      'セントロアメリカーノ', 'Centroamericano', 'centroamericano', '中央アメリカ',
      'Sarchimor系統とエチオピア系統を背景に持つF1ハイブリッドです．高い収量と良好な品質を狙える一方，種子繁殖では形質が分離するため，クローン苗の扱いが重要です．',
      '豆サイズ: 平均から大．', '高標高でVery Good評価を期待．F1らしい樹勢と品質を見る品種．', 'しっかり', '香りが出やすい', '平均',
      'アラビカ / F1 hybrid，introgressed', '高性から中間', '高い',
      'F1ハイブリッドで，苗の由来を確認したい品種です．',
      '耐病性と収量を期待できますが，地域差があります．',
      '沖縄ではクローン苗の入手性が前提になります．樹勢，収量，風味を一体で記録したい品種です．',
      '鉢では樹勢が強い場合があるため，大鉢で調整したいです．',
      '苗の由来が分かる場合に試したいです．',
      'F1品種の代表として入れておく価値があります．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのCentroamericano品種情報をもとに要約．', true, false
    ),
    (
      'スターマヤ', 'Starmaya', 'starmaya', '中央アメリカ',
      '種子生産を可能にする雄性不稔を利用したF1ハイブリッドです．F1系品種の中でも普及しやすい仕組みを持ち，品質と収量の両立を狙います．',
      '豆サイズ: 平均から大．', '高標高で良好な品質を期待．', 'バランス型', '穏やか', '平均',
      'アラビカ / F1 hybrid，introgressed', '矮性から中間', '高い',
      'F1ハイブリッドで，苗の品質管理が重要です．',
      '耐病性と収量を目的に比較したい品種です．',
      '沖縄では苗の由来が分かれば，樹勢と着果の安定性を試したい品種です．',
      '鉢でも若木観察は可能です．',
      '苗の入手経路が明確な場合に向きます．',
      '新しい育種の流れを示す品種として登録します．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのStarmaya品種情報をもとに要約．', true, false
    ),
    (
      'オバタ（赤）', 'Obata (Red)', 'obata-red', 'ブラジル',
      'Sarchimor系の背景を持つ赤実品種です．収量と耐病性を重視しながら，ブラジル系品種としての栽培性を見たい品種です．',
      '豆サイズ: 平均から大．', 'Good評価を期待する実用品種．', 'バランス型', '穏やか', '平均',
      'アラビカ / Introgressed，Sarchimor related', '矮性から中間', '高い',
      '比較的コンパクトに管理しやすいタイプです．',
      'さび病抵抗性を目的に選ばれる系統です．',
      '沖縄では耐病性と収量を重視した比較品種として使いやすいです．',
      '鉢でも候補になります．',
      '実用品種を試したい人向きです．',
      '赤実のSarchimor系として登録します．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのObata (Red)品種情報をもとに要約．', true, false
    ),
    (
      'ヴィラサルチ', 'Villa Sarchi', 'villa-sarchi', 'コスタリカ',
      'Bourbonの自然突然変異に由来する矮性品種です．高標高に適応し，強風への耐性があるとされます．豆はやや小さめで，Good評価の品質です．',
      '豆サイズ: やや小さめ．', '高標高でGood評価．', 'バランス型', '穏やか', '平均',
      'アラビカ / Bourbon-Typica group，Bourbon related', '矮性', '中',
      '矮性・コンパクトで，強風への耐性があるとされます．',
      'さび病，線虫，コーヒーベリー病には弱い評価です．',
      '沖縄ではコンパクトさと風への強さを見たい品種です．病害管理は必要です．',
      '鉢栽培候補です．樹形を低く作りやすいです．',
      '小スペース向きですが，病害には注意です．',
      '沖縄の防風条件で試してみたい品種です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: natural mutation of Bourbon，dwarf/compact，below average bean，Good quality，tolerant of strong winds．', true, false
    ),
    (
      'パカス', 'Pacas', 'pacas', 'エルサルバドル',
      'Bourbonの自然突然変異に由来する矮性品種です．コンパクトで管理しやすく，Pacamaraの親としても重要です．',
      '豆サイズ: 平均．', 'Good評価を期待．ブルボン系の比較品種．', 'バランス型', '穏やか', '平均',
      'アラビカ / Bourbon-Typica group，Bourbon related', '矮性', '中',
      '矮性で密植や低樹高管理に向きます．',
      '病害抵抗性は強くないため観察が必要です．',
      '沖縄では小さく作れるブルボン系として試しやすいです．',
      '鉢向きです．',
      '樹形が扱いやすく，家庭で比較しやすい品種です．',
      'Pacamaraの親として系譜面でも重要です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのPacas品種情報をもとに要約．', true, false
    ),
    (
      'テキシック', 'Tekisic', 'tekisic', 'エルサルバドル',
      'Bourbon系の選抜品種です．高標高での品質評価を目的に扱われ，ブルボンらしい品質を比較したい品種です．',
      '豆サイズ: 平均．', '高標高で良好な品質を期待．', 'なめらか', '穏やか', '平均',
      'アラビカ / Bourbon-Typica group，Bourbon related', '高性', '中',
      'ブルボン系らしい樹姿で管理します．',
      '病害抵抗性品種ではないため，葉の健全性を見たいです．',
      '沖縄では品質系ブルボンとして比較できます．強風と病害に注意します．',
      '鉢では樹高管理が必要です．',
      '比較栽培向きです．',
      'ブルボン系の選抜として登録します．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのTekisic品種情報をもとに要約．', true, false
    ),
    (
      'ベネシア', 'Venecia', 'venecia', 'コスタリカ',
      'Bourbonの自然突然変異に由来する矮性品種です．収穫が遅く，雨の多い地域で乾季収穫に合わせやすいとされます．さび病には非常に弱い品種です．',
      '豆サイズ: 大．', '高標高でGood評価．', 'バランス型', '穏やか', '遅い',
      'アラビカ / Bourbon-Typica group，Bourbon related', '矮性', '中',
      '矮性・コンパクトで，晩生です．',
      'さび病，線虫，コーヒーベリー病に弱い評価です．',
      '沖縄では晩生の成熟時期を記録したい品種です．台風期と収穫期の重なりを確認したいです．',
      '鉢でも試せます．',
      '晩生品種を比較したい人向きです．',
      '収穫時期の違いを見るために入れておきます．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: dwarf/compact，large bean，late ripening，very high susceptibility to rust．', true, false
    ),
    (
      'リマニ', 'Limani', 'limani', 'プエルトリコ',
      'Catimor関連の矮性品種です．さび病抵抗性と実用性を目的に使われるタイプで，低地から中標高での比較に向きます．',
      '豆サイズ: 平均．', '実用品質．耐病性と収量を比較したい品種．', 'バランス型', '穏やか', '平均',
      'アラビカ / Introgressed，Catimor related', '矮性', '高い',
      '矮性・コンパクトで管理しやすいタイプです．',
      'さび病抵抗性を目的に比較したい品種です．',
      '沖縄ではコンパクトな耐病性候補として有用です．味よりもまず樹の健全性と着果を記録したいです．',
      '鉢向きです．',
      '育てやすさを見たい人向きです．',
      '耐病性品種の比較枠として登録します．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのLimani品種情報をもとに要約．', true, false
    ),
    (
      'ルイロサルカ', 'RAB C15', 'rab-c15', 'ルワンダ',
      'ルワンダで育成された実用品種です．カタログではRAB C15として扱われ，収量や病害抵抗性を含む地域適応を比較する品種です．',
      '豆サイズ: 平均から大．', '地域適応と実用品質を比較．', 'バランス型', '穏やか', '平均',
      'アラビカ / Introgressed', '矮性から中間', '高い',
      '地域適応を目的に評価したい品種です．',
      '病害抵抗性と収量を園地で確認したいです．',
      '沖縄ではデータが少ないため，まず生育・開花・結実の記録を残したい品種です．',
      '鉢でも若木観察は可能です．',
      '比較栽培向きです．',
      'アフリカ育成系として登録します．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのRAB C15品種情報をもとに要約．', true, false
    ),
    (
      'AB3', 'AB3', 'ab3', 'インドネシア，ジャワ島で限定栽培',
      'エチオピア系ランドレース由来の高性品種です．アグロフォレストリーに適応し，大粒でGood評価の品質を持ちます．Pratylenchus線虫には弱いとされます．',
      '豆サイズ: 大．', '高標高でGood評価．', 'バランス型', '穏やか', '平均',
      'アラビカ / Ethiopian landrace', '高性', '中',
      '高性で，半日陰や混植条件に適応しやすいとされます．',
      'さび病は中間抵抗性，線虫には弱い評価です．',
      '沖縄では半日陰栽培との相性を見たい品種です．大粒性と葉の健全性を記録したいです．',
      '鉢では樹高管理が必要です．',
      '比較栽培向きです．',
      '半日陰での栽培比較に使いやすい品種です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: Ethiopian landrace，adapted for agroforestry，large bean，medium yield，intermediate rust resistance．', true, false
    ),
    (
      'ネマヤ', 'Nemaya (Coffea canephora)', 'nemaya', '中央アメリカで台木利用',
      'Coffea canephora系の線虫抵抗性台木として知られる品種です．主にアラビカの接ぎ木台として利用され，果実品質より根の健全性を目的に評価されます．',
      '豆サイズ: ロブスタ系．', '飲用品質より台木利用を重視．', '実用品質', 'ロブスタ系', '不明',
      'ロブスタ / Coffea canephora', '高性', '台木利用',
      '根系の強さを活かす台木候補です．',
      '線虫抵抗性を目的に扱われます．',
      '沖縄では接ぎ木台木としての可能性を見たい品種です．自根アラビカとの生育差を比較すると面白いです．',
      '鉢では台木試験や接ぎ木練習向きです．',
      '飲用果実目的ではなく，栽培技術の比較向きです．',
      'コーヒーの接ぎ木台木として図鑑に入れておきたいです．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: Coffea canephora rootstock，nematode resistant．', true, false
    ),
    (
      'BP 534', 'BP 534', 'bp-534', 'インドネシア',
      'インドネシアで広く栽培されるロブスタ系クローンです．湿潤気候のアグロフォレストリーに適し，大粒で1700-2200kg/ha程度の収量ポテンシャルが示されています．',
      '豆サイズ: 大（screen size >17）．', 'ロブスタ系の実用品質．', '力強い', 'ロブスタ系', '平均',
      'ロブスタ / Congo group', '高性', '1700-2200kg/ha',
      '高性で短節間，400-900m程度の湿潤地に適するとされます．',
      'さび病に高抵抗性，線虫抵抗性，ベリーボーラーには弱い評価です．他クローンとの混植が必要です．',
      '沖縄では高温多湿への適応を見たいロブスタ候補です．結実には他クローン混植を意識します．',
      '鉢では大きくなりやすく，クローン比較の観察向きです．',
      'ロブスタを試したい人向きです．',
      '高温多湿地での比較品種として面白いです．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: Indonesia clone，large bean，1700-2200kg/ha，high rust resistance，must be planted with other clones．', true, false
    ),
    (
      'BP 936', 'BP 936', 'bp-936', 'インドネシア',
      'インドネシアのロブスタ系クローンです．環境適応幅が広く，湿潤気候で生産性が出やすいとされます．大粒で1600-2200kg/ha程度の収量ポテンシャルがあります．',
      '豆サイズ: 大（screen size >17）．', 'ロブスタ系の実用品質．', '力強い', 'ロブスタ系', '平均',
      'ロブスタ / Congo group', '高性', '1600-2200kg/ha',
      '高性で，400-900m程度の湿潤地での生産性が高いとされます．',
      'さび病に高抵抗性，線虫抵抗性．Pratylenchus coffeaeには弱いとされ，他クローンとの混植が必要です．',
      '沖縄では湿潤条件への適応と樹勢を見たい品種です．単独植えでは結実性に注意します．',
      '鉢では樹勢確認向きです．',
      'ロブスタ比較向きです．',
      'BP 534と並べて比較したい品種です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: Indonesia clone，large bean，1600-2200kg/ha，wide adaptability，must be planted with other clones．', true, false
    ),
    (
      'キトゥザ・ロブスタ10', 'NARO-Kituza Robusta 10', 'naro-kituza-robusta-10', 'ウガンダ',
      'ウガンダのロブスタ系クローンです．コーヒー萎凋病と赤斑病に抵抗性があり，4800kg/ha程度の高い収量ポテンシャルが示されています．',
      '豆サイズ: 中（screen size 15-16）．', 'SCA 80点の記載があり，ロブスタとして品質も比較したい．', 'しっかり', 'ロブスタ系', '遅い',
      'ロブスタ / Uganda group', '高性', '4800kg/ha',
      '高性で，肥培要求は高めです．',
      'さび病に高抵抗性．萎凋病と赤斑病に抵抗性．結実には他クローン混植が必要です．',
      '沖縄では病害抵抗性と高収量性を見たいロブスタ候補です．台風時の樹高管理は課題になります．',
      '鉢では大きくなりやすいため，大鉢で比較観察向きです．',
      'ロブスタ系を複数系統で試せる場合に向きます．',
      '病害抵抗性の情報が明確で，実用性の高い候補です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: Uganda clone，4800kg/ha，late ripening，resistant to wilt and red blister，SCA 80，must be planted with other clones．', true, false
    ),
    (
      'キトゥザ・ロブスタ2', 'NARO-Kituza Robusta 2', 'naro-kituza-robusta-2', 'ウガンダ',
      'ウガンダのロブスタ系クローンです．コーヒー萎凋病と赤斑病に抵抗性があり，2600kg/ha程度の収量ポテンシャルとSCA 82点の記載があります．',
      '豆サイズ: 中（screen size 15-16）．', 'SCA 82点の記載があり，ロブスタ品質比較に向く．', 'しっかり', 'ロブスタ系', '遅い',
      'ロブスタ / Uganda group', '高性', '2600kg/ha',
      '高性で，肥培要求は高めです．',
      'さび病に高抵抗性．萎凋病と赤斑病に抵抗性．他クローン混植が必要です．',
      '沖縄では品質寄りのロブスタ比較品種として面白いです．開花と結実には混植条件を意識します．',
      '鉢では若木観察向きです．',
      '複数クローン栽培ができる場合に向きます．',
      'ロブスタの品質評価用として登録します．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: Uganda clone，2600kg/ha，late ripening，SCA 82，resistant to wilt and red blister，must be planted with other clones．', true, false
    ),
    (
      'キトゥザ・ロブスタ3', 'NARO-Kituza Robusta 3', 'naro-kituza-robusta-3', 'ウガンダ',
      'ウガンダのロブスタ系クローンです．4900kg/ha程度の高収量ポテンシャルが示され，萎凋病と赤斑病に抵抗性があります．',
      '豆サイズ: 中（screen size 15-16）．', 'SCA 78点の記載．高収量ロブスタとして比較．', 'しっかり', 'ロブスタ系', '遅い',
      'ロブスタ / Uganda group', '高性', '4900kg/ha',
      '高性で，肥培要求は高めです．',
      'さび病に高抵抗性．萎凋病と赤斑病に抵抗性．他クローン混植が必要です．',
      '沖縄では高収量性と樹勢を見たい品種です．防風と樹高管理をセットで考えたいです．',
      '鉢では樹勢確認が中心です．',
      'ロブスタ系の比較栽培向きです．',
      'キトゥザ系の中でも収量比較に入れておきたい品種です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: Uganda clone，4900kg/ha，late ripening，SCA 78，resistant to wilt and red blister，must be planted with other clones．', true, false
    ),
    (
      'サンルン', 'Xanh lun', 'xanh-lun', 'ベトナム',
      'ベトナムで選抜されたコンパクトなロブスタ系品種です．非常に高い収量ポテンシャル，晩生，大粒，乾燥への相対的な耐性が特徴です．',
      '豆サイズ: 大（screen size >17）．', 'ロブスタ系として高品質とされる実用品種．', '力強い', 'ロブスタ系', '遅い',
      'ロブスタ / Congo group', '矮性', '5000-6000kg/ha',
      '矮性・コンパクトで，500-800m程度が生産適地とされます．',
      'さび病は中間抵抗性．結実には他クローン混植が必要です．',
      '沖縄では樹形の低さと高収量性が魅力です．ロブスタ系を試すなら比較候補にしやすい品種です．',
      '鉢でも若木は扱いやすい可能性がありますが，収量を狙うなら大鉢以上が必要です．',
      'ロブスタを家庭で試す候補として面白いです．',
      '矮性ロブスタとして図鑑に入れておきたいです．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCR: Vietnam clone，dwarf/compact，large bean，5000-6000kg/ha，late ripening，relative drought tolerance．', true, false
    ),
    (
      'TR4', 'TR4', 'tr4', 'インド',
      'インドで扱われるロブスタ系品種です．ロブスタの収量性，病害抵抗性，栽培地域への適応を比較するための候補として登録します．',
      '豆サイズ: ロブスタ系．', 'ロブスタ系の実用品質．', '力強い', 'ロブスタ系', '不明',
      'ロブスタ / Coffea canephora', '高性', '高い',
      'ロブスタ系で樹勢が強いタイプとして扱います．',
      '詳細は園地観察で補正したい品種です．',
      '沖縄では高温多湿下での樹勢と着果を確認したい品種です．他クローンとの混植を意識します．',
      '鉢では観察向きです．',
      'ロブスタ比較向きです．',
      '今後，栽培記録で内容を濃くしたい品種です．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのTR4品種情報をもとに要約．', true, false
    ),
    (
      'TR9', 'TR9', 'tr9', 'インド',
      'インドで扱われるロブスタ系品種です．ロブスタ系統間の樹勢，結実性，品質を比較するために登録します．',
      '豆サイズ: ロブスタ系．', 'ロブスタ系の実用品質．', '力強い', 'ロブスタ系', '不明',
      'ロブスタ / Coffea canephora', '高性', '高い',
      'ロブスタ系で樹勢を確認したい品種です．',
      '詳細は園地観察で補正したい品種です．',
      '沖縄ではTR4やTR11と並べて比較し，開花同期と結実を見たい品種です．',
      '鉢では観察向きです．',
      'ロブスタ比較向きです．',
      '複数ロブスタを並べることで図鑑情報が増やせます．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのTR9品種情報をもとに要約．', true, false
    ),
    (
      'TR11', 'TR11', 'tr11', 'インド',
      'インドで扱われるロブスタ系品種です．高温多湿地での生育，収量，病害の出方を比較する品種として登録します．',
      '豆サイズ: ロブスタ系．', 'ロブスタ系の実用品質．', '力強い', 'ロブスタ系', '不明',
      'ロブスタ / Coffea canephora', '高性', '高い',
      'ロブスタ系で樹勢を確認したい品種です．',
      '詳細は園地観察で補正したい品種です．',
      '沖縄では高温期の生育と台風後の回復を見たい品種です．他クローン混植も考えたいです．',
      '鉢では若木観察向きです．',
      'ロブスタ比較向きです．',
      'TR系の比較品種として登録します．',
      '出典: World Coffee Research, Coffee Varieties Catalog, revised 2025-09-04.',
      'WCRカタログのTR11品種情報をもとに要約．', true, false
    )
  ) as v (
    name_ja,
    name_en,
    slug,
    origin,
    description,
    fruit_size,
    taste,
    texture,
    aroma,
    harvest_season,
    genome_group,
    plant_height_type,
    yield_level,
    tree_vigor,
    difficulty,
    okinawa_suitability,
    container_suitability,
    beginner_suitability,
    kenyu_comment,
    public_notes,
    private_notes,
    is_public,
    is_for_sale
  )
)
insert into public.cultivars (
  fruit_id,
  name_ja,
  name_en,
  slug,
  origin,
  description,
  fruit_size,
  taste,
  texture,
  aroma,
  harvest_season,
  genome_group,
  plant_height_type,
  yield_level,
  tree_vigor,
  difficulty,
  okinawa_suitability,
  container_suitability,
  beginner_suitability,
  kenyu_comment,
  public_notes,
  private_notes,
  is_public,
  is_for_sale
)
select
  coffee.id,
  new_cultivars.name_ja,
  new_cultivars.name_en,
  new_cultivars.slug,
  new_cultivars.origin,
  new_cultivars.description,
  new_cultivars.fruit_size,
  new_cultivars.taste,
  new_cultivars.texture,
  new_cultivars.aroma,
  new_cultivars.harvest_season,
  new_cultivars.genome_group,
  new_cultivars.plant_height_type,
  new_cultivars.yield_level,
  new_cultivars.tree_vigor,
  new_cultivars.difficulty,
  new_cultivars.okinawa_suitability,
  new_cultivars.container_suitability,
  new_cultivars.beginner_suitability,
  new_cultivars.kenyu_comment,
  new_cultivars.public_notes,
  new_cultivars.private_notes,
  new_cultivars.is_public,
  new_cultivars.is_for_sale
from new_cultivars
cross join coffee
on conflict (fruit_id, slug) do update set
  name_ja = excluded.name_ja,
  name_en = excluded.name_en,
  origin = excluded.origin,
  description = excluded.description,
  fruit_size = excluded.fruit_size,
  taste = excluded.taste,
  texture = excluded.texture,
  aroma = excluded.aroma,
  harvest_season = excluded.harvest_season,
  genome_group = excluded.genome_group,
  plant_height_type = excluded.plant_height_type,
  yield_level = excluded.yield_level,
  tree_vigor = excluded.tree_vigor,
  difficulty = excluded.difficulty,
  okinawa_suitability = excluded.okinawa_suitability,
  container_suitability = excluded.container_suitability,
  beginner_suitability = excluded.beginner_suitability,
  kenyu_comment = excluded.kenyu_comment,
  public_notes = excluded.public_notes,
  private_notes = excluded.private_notes,
  is_public = excluded.is_public,
  is_for_sale = excluded.is_for_sale,
  updated_at = now();

select
  f.name_ja as fruit_name,
  count(c.id) as coffee_cultivar_count
from public.fruits f
left join public.cultivars c on c.fruit_id = f.id
where f.slug = 'coffee'
group by f.name_ja;

commit;
