with fruit as (
  select id from public.fruits where slug = 'guava'
), cultivar_source as (
  select * from (values
    (
      '真珠グァバ',
      'Jen-Ju Bar / Pearl Guava',
      'pearl-guava',
      '台湾',
      '台湾の主要なデザートグァバ品種。淡緑色の果皮、白肉、シャキシャキした硬めの食感、低い香り、長い日持ちが特徴です。台湾では輸出向けにも重要で、成熟緑色のまま販売しやすい非クライマクテリック型として研究されています。',
      '中から大。台湾系では果形がそろいやすく、袋掛けで外観を整えやすい。',
      '爽やかな甘味。台湾高雄市の紹介では真珠グァバは10から15度程度の糖度が目安とされます。',
      '硬めでクリスピー',
      '控えめ',
      '台湾では周年生産。品質のよい時期は秋から冬に評価されやすい。',
      null,
      null,
      null,
      null,
      '台湾系の代表候補。沖縄では高温期の果実品質、台風後の枝回復、ミバエ対策を見ながら、袋掛けで外観を作りたい。',
      '鉢でも若木の観察は可能。長期的には根量と水切れに注意。',
      '硬肉・低香タイプで食べやすく、家庭栽培の基準品種として比較しやすい。',
      '台湾系グァバの基準にしたい品種。香りよりも歯触り、日持ち、低種子感を評価したいです。',
      '出典: Chen et al. 2023 Postharvest Biology and Technology / Taiwan MOA Guava / Kaohsiung Agriculture Guava.',
      'JJB / Jen-Ju Bar / 珍珠芭樂。台湾では真珠グァバが主要品種として扱われる。'
    ),
    (

      '帝王グァバ',
      'Tainung No.1 / Emperor',
      'emperor-guava',
      '台湾',
      '台湾農業試験所が紹介する台農1号・帝王。樹勢が強く多収で、果実は中から大玉、緑黄色の果皮、厚い白肉、クリスピーな食感が特徴です。TARIの紹介では平均収量35t/ha、貯蔵性は1度で3から4週間とされています。',
      '中から大。厚い白肉で歩留まりがよい。',
      '可溶性固形物が高く、ビタミンCと抗酸化成分が豊富とされる。',
      '厚肉でクリスピー',
      '穏やか',
      '台湾では周年生産。沖縄では開花時期と台風時期の重なりを記録したい。',
      null,
      null,
      '強い',
      '多い',
      '樹勢と収量を重視するなら候補。沖縄では着果過多にすると果実が小さくなりやすいため、摘果と袋掛けを組み合わせたい。',
      '大鉢でも試せるが、樹勢が強いため剪定で樹高を抑えたい。',
      '管理できるスペースがあれば有望。収量性が高い分、摘果と肥培管理を覚える必要があります。',
      '「帝王」という名前どおり、樹勢と収量の基準として見たい品種。真珠と並べて食感と果実サイズを比較したいです。',
      '出典: TARI Tainung No.1 Emperor.',
      '台農1号 / 帝王芭樂。'
    ),
    (

      '水晶グァバ',
      'Crystal Guava',
      'crystal-guava',
      '台湾',
      '台湾で改良・普及している硬肉系グァバの一つ。厚い果肉とクリスピーな食感で知られ、真珠、帝王と並んで果実品質向上の対象として紹介されています。',
      '中から大。低種子感と厚肉性を評価したい。',
      'すっきりした甘味。食味は収穫時期と袋掛け管理で変わりやすい。',
      '厚肉でクリスピー',
      '控えめ',
      '周年生産型。沖縄では秋冬果の品質を特に見たい。',
      null,
      null,
      '中から強い',
      '中から多い',
      '沖縄では真珠・帝王と並べて、食感、種の硬さ、外観、裂果の出方を比較したい。',
      '鉢では樹形を小さく保てば試作向き。',
      '硬肉系が好きな人には扱いやすい候補。',
      '「硬くてシャキッと食べるグァバ」の比較用として入れておきたい品種です。',
      '出典: Taiwan MOA Guava / TARI Tropical Fruit Trees.',
      '水晶芭樂。'
    ),
    (

      '梨仔抜',
      'Pear Guava',
      'pear-guava',
      '台湾',
      '台湾で古くから知られる梨形・梨食感系のグァバ。果肉が厚く、クリスピーで香りがあり、台湾農業部の紹介では梨グァバは厚くパリッとした果肉と香りが特徴とされています。',
      '洋梨形から丸みのある形。果肉が厚い。',
      '軽い甘味と爽やかな香り。',
      '梨のように硬め',
      '爽やか',
      '台湾では周年生産。沖縄では秋から冬の果実品質を見たい。',
      null,
      null,
      '中',
      '中',
      '沖縄では果形のそろい、果肉の厚さ、香り、種の硬さを記録したい。台湾系の食感を楽しむ品種として候補。',
      '鉢でも若木は観察しやすい。',
      '食感が分かりやすく、食べ比べに向く。',
      '梨のような歯触りを評価したい品種。真珠より香りが出るかを見たいです。',
      '出典: Taiwan MOA Guava / Japan Fruit guava overview.',
      '梨仔抜 / 梨仔拔 / Pear guava。'
    ),
    (

      '台湾梨グァバ',
      'Taiwanese Pear Guava',
      'taiwanese-pear-guava',
      '台湾・ベトナム',
      '台湾由来の梨グァバ系統がベトナムでも栽培されている流通名。ベトナムNghe Anの記事では、果実が大きく、果肉が厚く、種が少なく、甘く香る点が長所として紹介されています。',
      '大きめ。果肉が厚く、種が少ないタイプとして扱われる。',
      '甘く香りがある。若採りではシャキシャキ感が出やすい。',
      '硬めから中程度',
      'あり',
      'ベトナムでは周年的に栽培しやすいと紹介される。沖縄でも周年開花・結実の記録を取りたい。',
      null,
      null,
      '強め',
      '中から多い',
      '沖縄では導入しやすいアジア系グァバ候補。ミバエ対策と袋掛けを前提に、大玉性と食味を見たい。',
      '鉢でも試せるが、大玉を狙うなら露地または大鉢向き。',
      '樹勢が強く作りやすい可能性があり、初心者にも候補。',
      'ベトナムで人気の梨グァバとして、沖縄での実用性を見たい品種です。',
      '出典: Baonghean pear guava / VietnamOnline Vietnamese Guava.',
      'Ổi lê Đài Loan / Vietnamese pear guava。'
    ),
    (

      '女王グァバ',
      'Queen Guava / Oi Nu Hoang',
      'queen-guava',
      'ベトナム',
      'ベトナムで人気のある大型系グァバ。VietnamOnlineでは球形で平均350から400g、種が少なく、白くクリスピーな果肉をもつタイプとして紹介されています。',
      '350から400g前後の大玉目安。',
      '爽やかな甘味。硬めで食べやすい。',
      '白肉でクリスピー',
      '穏やか',
      'ベトナムでは周年的に見られる。沖縄では夏秋果と冬春果で品質を比較したい。',
      null,
      null,
      '中から強い',
      '中から多い',
      '大玉で低種子系を狙うなら候補。沖縄では摘果と袋掛けでサイズと外観を整えたい。',
      '大玉を狙うなら鉢より露地向き。',
      '収穫できると満足度が高いが、摘果管理は必要。',
      '大玉・少種子・白肉という、家庭向けに分かりやすい魅力がある品種です。',
      '出典: VietnamOnline Vietnamese Guava / Vinpearl Vietnamese guava.',
      'Ổi nữ hoàng。'
    ),
    (

      'サーリーゲー',
      'Oi Xa Li Nghe',
      'oi-xa-li-nghe',
      'ベトナム',
      'ベトナムのメコンデルタなどで栽培される大果・低種子系として紹介されるグァバ。VietnamOnlineではアメリカから導入された品種で、大きく種が少ないタイプとされています。',
      '大きめ。低種子系。',
      '爽やかな甘味。若採りでは硬く食べやすい。',
      '硬め',
      '控えめ',
      'ベトナムでは地域栽培がある。沖縄では収穫期の幅を記録したい。',
      null,
      null,
      '中',
      '中',
      '大果・低種子系として比較したい。沖縄では樹勢、着果量、果肉の硬さを見たい。',
      '大鉢なら試作可能。',
      '低種子タイプとして食べやすい候補。',
      'ベトナム系の食べ比べ用に入れておきたい品種です。',
      '出典: VietnamOnline Vietnamese Guava.',
      'Ổi xá lị Nghệ。'
    ),
    (

      'ボーグァバ',
      'Oi Bo',
      'oi-bo',
      'ベトナム',
      'ベトナムThai Binh周辺の品種として紹介される大型グァバ。VietnamOnlineでは直径8から13cm程度、クリスピーで甘いタイプとされています。',
      '直径8から13cm程度の大きめ。',
      '甘く、若採りでも食べやすい。',
      'クリスピー',
      '穏やか',
      'ベトナムではThai BinhやHai Duongで栽培と紹介される。',
      null,
      null,
      '中',
      '中',
      '沖縄では果実サイズと硬さを記録したい。大玉系として摘果の効果を見たい。',
      '鉢でも試せるが、大玉は露地向き。',
      '食味が分かりやすく、比較しやすい。',
      'ベトナム北部系の大型グァバとして整理しておきたい品種です。',
      '出典: VietnamOnline Vietnamese Guava.',
      'Ổi bo。'
    ),
    (

      '紅心グァバ',
      'Pink Guava / Oi Ruot Hong',
      'pink-guava',
      '熱帯アメリカ・アジア各地',
      '果肉中心部が桃色から赤色になるグァバ。VietnamOnlineでは250から500g程度で、甘く、完熟しても歯触りが残るタイプが紹介されています。加工、ジュース、生食で香りを楽しめます。',
      '中から大。250から500g程度の系統もある。',
      '甘味と酸味、香りのバランス。完熟香が出やすい。',
      '白肉系より柔らかめから中程度',
      '強め',
      '暖地では複数回開花することがある。',
      null,
      null,
      '中',
      '中',
      '沖縄では香りの強いグァバとして重要。ミバエ対策を徹底し、加工用・生食用の両方で評価したい。',
      '鉢でも実をつけやすい候補。',
      '香りが出るため満足度は高いが、熟度管理と虫対策が必要。',
      '白肉台湾系とは別の方向で、香りを楽しむ品種として残したいです。',
      '出典: VietnamOnline Vietnamese Guava / Taiwan MOA Guava.',
      'Ổi ruột hồng / Pink guava。'
    )
  ) as v(
    name_ja,
    name_en,
    slug,
    origin,
    description,
    fruit_size,
    taste,
    texture,
    aroma,
    harvest_season,
    cold_hardiness,
    flowering_type,
    tree_vigor,
    yield_level,
    okinawa_suitability,
    container_suitability,
    beginner_suitability,
    kenyu_comment,
    public_notes,
    private_notes
  )
)
insert into public.cultivars (
  fruit_id,
  name_ja,
  name_en,
  slug,
  origin,
  description,
  fruit_size,
  taste,
  texture,
  aroma,
  harvest_season,
  cold_hardiness,
  flowering_type,
  tree_vigor,
  yield_level,
  difficulty,
  okinawa_suitability,
  container_suitability,
  beginner_suitability,
  kenyu_comment,
  public_notes,
  private_notes,
  is_public,
  is_for_sale
)
select
  fruit.id,
  cultivar_source.name_ja,
  cultivar_source.name_en,
  cultivar_source.slug,
  cultivar_source.origin,
  cultivar_source.description,
  cultivar_source.fruit_size,
  cultivar_source.taste,
  cultivar_source.texture,
  cultivar_source.aroma,
  cultivar_source.harvest_season,
  cultivar_source.cold_hardiness,
  cultivar_source.flowering_type,
  cultivar_source.tree_vigor,
  cultivar_source.yield_level,
  'グァバは生育が早く作りやすい一方、果実品質は摘果、袋掛け、ミバエ対策で大きく変わります。',
  cultivar_source.okinawa_suitability,
  cultivar_source.container_suitability,
  cultivar_source.beginner_suitability,
  cultivar_source.kenyu_comment,
  cultivar_source.public_notes,
  cultivar_source.private_notes,
  true,
  false
from cultivar_source
cross join fruit
on conflict (fruit_id, slug) do update set
  name_ja = excluded.name_ja,
  name_en = excluded.name_en,
  origin = excluded.origin,
  description = excluded.description,
  fruit_size = excluded.fruit_size,
  taste = excluded.taste,
  texture = excluded.texture,
  aroma = excluded.aroma,
  harvest_season = excluded.harvest_season,
  cold_hardiness = excluded.cold_hardiness,
  flowering_type = excluded.flowering_type,
  tree_vigor = excluded.tree_vigor,
  yield_level = excluded.yield_level,
  difficulty = excluded.difficulty,
  okinawa_suitability = excluded.okinawa_suitability,
  container_suitability = excluded.container_suitability,
  beginner_suitability = excluded.beginner_suitability,
  kenyu_comment = excluded.kenyu_comment,
  public_notes = excluded.public_notes,
  private_notes = excluded.private_notes,
  is_public = excluded.is_public,
  is_for_sale = excluded.is_for_sale,
  updated_at = now();

select count(*) as guava_cultivar_count from public.cultivars where fruit_id = (select id from public.fruits where slug = 'guava');
