with fruit as (
  select id from public.fruits where slug = 'guava'
), cultivar_source as (
  select * from (values
    (

      '紫グァバ',
      'Purple Guava / Oi Tim',
      'purple-guava',
      'ベトナム・熱帯地域',
      '紫色を帯びるグァバ系統。VietnamOnlineでは紫色で柔らかく、種が少なく、周年的に実るタイプとして紹介されています。',
      '中程度。',
      '甘味と香りを楽しむタイプ。',
      '柔らかめ',
      'あり',
      '周年的に結実する系統として紹介される。',
      null,
      null,
      '中',
      '中',
      '沖縄では果皮色・果肉色の観賞性も含めて評価したい。熟しすぎると傷みやすいため収穫適期に注意。',
      '鉢でも観察向き。',
      '色の変化が楽しく、図鑑向き。',
      '見た目の個性が強いので、写真を残したい品種です。',
      '出典: VietnamOnline Vietnamese Guava.',
      'Ổi tím。'
    ),
    (

      'ギャングァバ',
      'Oi Gang',
      'oi-gang',
      'ベトナム',
      'ベトナムで見られる小果系グァバ。VietnamOnlineでは直径4から5cm程度で、とてもクリスピーで甘いタイプとして紹介されています。',
      '小さめ。直径4から5cm程度。',
      '小果ながら甘味があり、若採りでも食べやすい。',
      '非常にクリスピー',
      '控えめ',
      'ベトナムではGia Lam, Hanoi周辺で見られると紹介される。',
      null,
      null,
      '中',
      '中',
      '沖縄では小果で食べやすい系統として、家庭向けの収穫しやすさを見たい。',
      '鉢向き候補。',
      '小果で扱いやすく、初心者の観察に向く可能性があります。',
      '小さくても味がよければ家庭栽培で便利な品種になります。',
      '出典: VietnamOnline Vietnamese Guava.',
      'Ổi găng。'
    ),
    (

      '桃肉グァバ',
      'Oi Dao',
      'oi-dao',
      'ベトナム',
      '桃色の中心部をもつ小果系グァバ。VietnamOnlineでは小さめで、柔らかい果肉とピンクの中心部をもつタイプとして紹介されています。',
      '小から中。',
      '香りと甘酸っぱさを楽しむタイプ。',
      '柔らかめ',
      'あり',
      'ベトナムで流通する小果系。',
      null,
      null,
      '中',
      '中',
      '沖縄では加工・ジュース・香りの評価に向く。完熟果は傷みやすいため収穫後すぐ使いたい。',
      '鉢でも試しやすい。',
      '香り系が好きなら候補。',
      '桃色の果肉は写真映えするので、図鑑で残したい品種です。',
      '出典: VietnamOnline Vietnamese Guava.',
      'Ổi đào。'
    ),
    (

      '白肉グァバ',
      'White Guava',
      'white-guava',
      '台湾・熱帯各地',
      '白い果肉をもつグァバの総称的な品種群。台湾農業部では白肉系は透明感のある果皮と爽やかな歯触りで、台湾の市場でも重要なグループとして紹介されています。',
      '系統差が大きい。',
      '爽やかな甘味。香りは控えめから中程度。',
      'クリスピーから中程度',
      '控えめ',
      '周年生産される地域が多い。',
      null,
      null,
      '中',
      '中',
      '沖縄では台湾系硬肉品種と在来・実生系の比較対象として重要。',
      '鉢でも試作可能。',
      '基準品種として比較しやすい。',
      '白肉系はグァバの基準枠として残しておきたいです。',
      '出典: Taiwan MOA Guava.',
      'White-flesh guava group。'
    ),
    (

      'タイグァバ',
      'Thai Guava',
      'thai-guava',
      'タイ',
      'タイで多く食べられる硬肉系グァバ。台湾農業部の紹介では、タイグァバは糖度が低めでクリスピーな食感をもつグループとして扱われています。',
      '中から大。',
      '甘さは控えめで、歯触りを楽しむタイプ。',
      '硬くクリスピー',
      '控えめ',
      '熱帯アジアで広く栽培。',
      null,
      null,
      '中から強い',
      '中',
      '沖縄では高温適性と硬肉性を比較したい。塩や唐辛子と食べるアジア的な利用にも向く。',
      '鉢でも試せる。',
      '甘い果物というより、食感を楽しむ果樹として育てたい。',
      '台湾系とはまた違う硬さと利用法を見たい品種です。',
      '出典: Taiwan MOA Guava.',
      'Thai guava group。'
    ),
    (

      'アラハバードサフェダ',
      'Allahabad Safeda',
      'allahabad-safeda',
      'インド',
      'インドを代表する白肉系グァバ品種。果皮は淡黄緑から黄白色、果肉は白く、甘味と香りのバランスがよい生食・加工兼用品種として知られます。',
      '中から大。',
      '甘味と香りのバランスがよい。',
      '中程度',
      'あり',
      '地域により冬から春、雨季後などに収穫。',
      null,
      null,
      '中',
      '中から多い',
      '沖縄では香りのある白肉系として、台湾硬肉系との違いを比較したい。',
      '鉢でも試せるが、品質安定には露地向き。',
      '食味はよいが、熟度管理と虫対策が必要。',
      'インド系の代表として入れておきたい品種です。',
      '出典: general horticultural cultivar references / guava cultivar literature.',
      'インドの代表的白肉品種。'
    ),
    (

      'サルダール',
      'Lucknow 49 / Sardar',
      'lucknow-49-sardar',
      'インド',
      'インドで広く知られる商用品種。果実は比較的大きく、果肉は白く、収量性と品質の安定性で評価されます。',
      '中から大。',
      '甘味と酸味のバランス。',
      '中程度',
      'あり',
      '地域により複数作型。',
      null,
      null,
      '強め',
      '多い',
      '沖縄では収量性と樹勢を比較したい。袋掛けと摘果で外観とサイズを整えたい。',
      '鉢より露地向き。',
      '樹勢が出るため剪定管理を覚えたい。',
      '収量性を見るための比較品種として有用です。',
      '出典: general horticultural cultivar references / guava cultivar literature.',
      'Lucknow-49 / Sardar。'
    ),
    (

      'ルビーシュプリーム',
      'Ruby Supreme',
      'ruby-supreme',
      'アメリカ・フロリダ',
      '米国フロリダで知られる紅肉系グァバ。加工にも向く香りと色を持ち、ジュース、ジャム、ピューレ用途でも評価される品種です。',
      '中程度。',
      '甘酸っぱく香りが強い。',
      '柔らかめから中程度',
      '強い',
      '温暖地では夏から秋中心。',
      null,
      null,
      '中',
      '中',
      '沖縄では加工向け・香り系として重要。完熟果の傷みとミバエ対策に注意したい。',
      '鉢でも試せる。',
      '香りが強く楽しいが、完熟管理が必要。',
      'ジャムやジュースまで含めて使える紅肉系として残したい品種です。',
      '出典: general horticultural cultivar references / guava cultivar literature.',
      'Ruby Supreme pink guava。'
    ),
    (

      'ホームステッド',
      'Homestead',
      'homestead-guava',
      'アメリカ・フロリダ',
      'フロリダで育成・流通したグァバ品種。白肉系として扱われることが多く、家庭果樹としての比較対象にしやすい品種です。',
      '中程度。',
      '爽やかな甘味。',
      '中程度',
      '中',
      '温暖地では夏から秋中心。',
      null,
      null,
      '中',
      '中',
      '沖縄では白肉系の香り、樹勢、病害虫の出方を比較したい。',
      '鉢でも試作可能。',
      '比較品種として扱いやすい。',
      '流通名が混ざりやすいので、導入株の特徴を写真で残したい品種です。',
      '出典: general horticultural cultivar references / guava cultivar literature.',
      'Homestead guava。'
    )
  ) as v(
    name_ja,
    name_en,
    slug,
    origin,
    description,
    fruit_size,
    taste,
    texture,
    aroma,
    harvest_season,
    cold_hardiness,
    flowering_type,
    tree_vigor,
    yield_level,
    okinawa_suitability,
    container_suitability,
    beginner_suitability,
    kenyu_comment,
    public_notes,
    private_notes
  )
)
insert into public.cultivars (
  fruit_id,
  name_ja,
  name_en,
  slug,
  origin,
  description,
  fruit_size,
  taste,
  texture,
  aroma,
  harvest_season,
  cold_hardiness,
  flowering_type,
  tree_vigor,
  yield_level,
  difficulty,
  okinawa_suitability,
  container_suitability,
  beginner_suitability,
  kenyu_comment,
  public_notes,
  private_notes,
  is_public,
  is_for_sale
)
select
  fruit.id,
  cultivar_source.name_ja,
  cultivar_source.name_en,
  cultivar_source.slug,
  cultivar_source.origin,
  cultivar_source.description,
  cultivar_source.fruit_size,
  cultivar_source.taste,
  cultivar_source.texture,
  cultivar_source.aroma,
  cultivar_source.harvest_season,
  cultivar_source.cold_hardiness,
  cultivar_source.flowering_type,
  cultivar_source.tree_vigor,
  cultivar_source.yield_level,
  'グァバは生育が早く作りやすい一方、果実品質は摘果、袋掛け、ミバエ対策で大きく変わります。',
  cultivar_source.okinawa_suitability,
  cultivar_source.container_suitability,
  cultivar_source.beginner_suitability,
  cultivar_source.kenyu_comment,
  cultivar_source.public_notes,
  cultivar_source.private_notes,
  true,
  false
from cultivar_source
cross join fruit
on conflict (fruit_id, slug) do update set
  name_ja = excluded.name_ja,
  name_en = excluded.name_en,
  origin = excluded.origin,
  description = excluded.description,
  fruit_size = excluded.fruit_size,
  taste = excluded.taste,
  texture = excluded.texture,
  aroma = excluded.aroma,
  harvest_season = excluded.harvest_season,
  cold_hardiness = excluded.cold_hardiness,
  flowering_type = excluded.flowering_type,
  tree_vigor = excluded.tree_vigor,
  yield_level = excluded.yield_level,
  difficulty = excluded.difficulty,
  okinawa_suitability = excluded.okinawa_suitability,
  container_suitability = excluded.container_suitability,
  beginner_suitability = excluded.beginner_suitability,
  kenyu_comment = excluded.kenyu_comment,
  public_notes = excluded.public_notes,
  private_notes = excluded.private_notes,
  is_public = excluded.is_public,
  is_for_sale = excluded.is_for_sale,
  updated_at = now();

select count(*) as guava_cultivar_count from public.cultivars where fruit_id = (select id from public.fruits where slug = 'guava');
