-- マンゴー品種のThe Mango由来説明を残しながら，JIRCAS数値データを追記します．
-- 目的: 糖度，酸度，果実重，成熟日数，果皮色などのJIRCAS情報を欠損させない．
-- 出典: JIRCASマンゴー遺伝資源サイト https://www.jircas.go.jp/ja/database/mango/mango-database

begin;

with mango as (
  select id
  from public.fruits
  where slug = 'mango'
  limit 1
),
source (name_ja, name_en, slug, origin, description, fruit_size, taste, texture, aroma, harvest_season, difficulty, okinawa_suitability, container_suitability, beginner_suitability, kenyu_comment, public_notes, is_public) as (
  values
  ('アーピン', 'Ah Ping', 'ah-ping', 'アメリカ（ハワイ）', 'アメリカ（ハワイ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-001として整理されています．', '423g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度16.5度，酸度0.18%です．', null, '個性的な香り', '成熟日数の中央値は132日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '個性が強く好みが分かれやすい', 'アーピンはアメリカ（ハワイ）のマンゴーで，中玉の果実です．糖度は中程度で酸味は中程度．果皮色は赤．個性的な香り．個性が強く好みが分かれやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-001）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-001.pdf', true),
  ('アンダーソン', 'Anderson', 'anderson', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-004として整理されています．', '931g（JIRCAS調査平均）．かなり大玉の部類．', '糖度は中程度，酸味はやや強め．JIRCAS調査値は糖度17.3度，酸度0.33%です．', null, null, '成熟日数の中央値は138日（JIRCAS石垣調査）．', '果皮表面のヤニに注意', 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'アンダーソンはアメリカ（フロリダ）のマンゴーで，かなり大玉の部類の果実です．糖度は中程度で酸味はやや強め．果皮色は黄と橙．果皮表面のヤニに注意．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-004）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-004.pdf', true),
  ('ベイリーズ マーベル', 'Bailey''s Marvel', 'baileys-marvel', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-005として整理されています．', '482g（JIRCAS調査平均）．中玉．', '糖度は非常に高い，酸味は強め．JIRCAS調査値は糖度21.0度，酸度0.40%です．', null, null, '成熟日数の中央値は144日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'ベイリーズ マーベルはアメリカ（フロリダ）のマンゴーで，中玉の果実です．糖度が非常に高く酸味は強め．果皮色は緑と黄．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-005）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-005.pdf', true),
  ('ベッキー', 'Becky', 'becky', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-006として整理されています．', '582g（JIRCAS調査平均）．大玉寄り．', '甘さは控えめ，酸味はやや強め．JIRCAS調査値は糖度13.9度，酸度0.29%です．', null, null, '成熟日数の中央値は148日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'ベッキーはアメリカ（フロリダ）のマンゴーで，大玉寄りの果実です．甘さは控えめで酸味はやや強め．果皮色は黄と橙．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-006）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-006.pdf', true),
  ('ベバリー', 'Beverly', 'beverly', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-007として整理されています．', '423g（JIRCAS調査平均）．中玉．', '糖度は高め，酸味は強め．JIRCAS調査値は糖度18.0度，酸度0.45%です．', null, null, '成熟日数の中央値は132日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '個性が強く好みが分かれやすい', 'ベバリーはアメリカ（フロリダ）のマンゴーで，中玉の果実です．糖度が高めで酸味は強め．果皮色は緑と黄．個性が強く好みが分かれやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-007）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-007.pdf', true),
  ('カラバオ', 'Carabao', 'carabao', 'フィリピン', 'フィリピンに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-008として整理されています．', '325g（JIRCAS調査平均）．小ぶり．', '糖度は中程度，酸味はやや強め．JIRCAS調査値は糖度15.9度，酸度0.27%です．', null, null, '成熟日数の中央値は132日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'カラバオはフィリピンのマンゴーで，小ぶりの果実です．糖度は中程度で酸味はやや強め．果皮色は黄橙．ペリカンマンゴーとして紹介されることがあります．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-008）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-008.pdf', true),
  ('チョカナン', 'Choke Anan', 'choke-anan', 'タイ', 'タイに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-011として整理されています．', '275g（JIRCAS調査平均）．小ぶり．', '糖度は高め，酸味は中程度．JIRCAS調査値は糖度19.1度，酸度0.16%です．', null, '個性的な香り', '成熟日数の中央値は130日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'チョカナンはタイのマンゴーで，小ぶりの果実です．糖度が高めで酸味は中程度．果皮色は黄橙．個性的な香り．食味のまとまりがあり試しやすい．JIRCASの試食会で評価された記録があります．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-011）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-011.pdf', true),
  ('クッシュマン', 'Cushman', 'cushman', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-012として整理されています．', '319g（JIRCAS調査平均）．小ぶり．', '糖度は高め，酸味はやや強め．JIRCAS調査値は糖度18.6度，酸度0.29%です．', null, null, '成熟日数の中央値は129日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'クッシュマンはアメリカ（フロリダ）のマンゴーで，小ぶりの果実です．糖度が高めで酸味はやや強め．果皮色は黄橙．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-012）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-012.pdf', true),
  ('ドット', 'Dot', 'dot', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-013として整理されています．', '379g（JIRCAS調査平均）．中玉．', '糖度は高め，酸味はやや強め．JIRCAS調査値は糖度19.3度，酸度0.25%です．', null, null, '成熟日数の中央値は130日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '個性が強く好みが分かれやすい', 'ドットはアメリカ（フロリダ）のマンゴーで，中玉の果実です．糖度が高めで酸味はやや強め．果皮色は黄と橙．個性が強く好みが分かれやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-013）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-013.pdf', true),
  ('ダンカン', 'Duncan', 'duncan', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-014として整理されています．', '598g（JIRCAS調査平均）．大玉寄り．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度17.4度，酸度0.15%です．', null, null, '成熟日数の中央値は149日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '甘味主体で受け入れられやすい', 'ダンカンはアメリカ（フロリダ）のマンゴーで，大玉寄りの果実です．糖度は中程度で酸味は中程度．果皮色は黄．甘味主体で受け入れられやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-014）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-014.pdf', true),
  ('エドワード', 'Edward', 'edward', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-015として整理されています．', '422g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度16.7度，酸度0.22%です．', null, '香りが良い', '成熟日数の中央値は124日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'エドワードはアメリカ（フロリダ）のマンゴーで，中玉の果実です．糖度は中程度で酸味は中程度．果皮色は黄橙．香りが良い．食味のまとまりがあり試しやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-015）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-015.pdf', true),
  ('ファッシル', 'Fascell', 'fascell', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-017として整理されています．', '549g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は強め．JIRCAS調査値は糖度15.3度，酸度0.44%です．', 'ややしっかりした肉質', null, '成熟日数の中央値は129日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'ファッシルはアメリカ（フロリダ）のマンゴーで，中玉の果実です．糖度は中程度で酸味は強め．果皮色は橙と赤．肉質はややしっかりした肉質．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-017）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-017.pdf', true),
  ('フクダ', 'Fukuda', 'fukuda', 'アメリカ（ハワイ）', 'アメリカ（ハワイ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-018として整理されています．', '516g（JIRCAS調査平均）．中玉．', '糖度は非常に高い，酸味はやや強め．JIRCAS調査値は糖度20.4度，酸度0.26%です．', null, '香りは強め', '成熟日数の中央値は139日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'フクダはアメリカ（ハワイ）のマンゴーで，中玉の果実です．糖度が非常に高く酸味はやや強め．果皮色は黄と橙．香りは強め．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-018）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-018.pdf', true),
  ('グレン', 'Glenn', 'glenn', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-019として整理されています．', '489g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は穏やか．JIRCAS調査値は糖度15.9度，酸度0.11%です．', null, null, '成熟日数の中央値は123日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'グレンはアメリカ（フロリダ）のマンゴーで，中玉の果実です．糖度は中程度で酸味は穏やか．果皮色は橙と赤．食味のまとまりがあり試しやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-019）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-019.pdf', true),
  ('ゴールデン ナゲット', 'Golden Nugget', 'golden-nugget', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-021として整理されています．', '425g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味はやや強め．JIRCAS調査値は糖度17.2度，酸度0.31%です．', 'なめらかで口当たりがよいタイプ', null, '成熟日数の中央値は141日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'ゴールデン ナゲットはアメリカ（フロリダ）のマンゴーで，中玉の果実です．糖度は中程度で酸味はやや強め．果皮色は黄橙．肉質はなめらかで口当たりがよいタイプ．食味のまとまりがあり試しやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-021）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-021.pdf', true),
  ('ゴレック', 'Goleck', 'goleck', 'インドネシア', 'インドネシアに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-022として整理されています．', '191g（JIRCAS調査平均）．小ぶり．', '糖度は高め，酸味はやや強め．JIRCAS調査値は糖度18.8度，酸度0.26%です．', '繊維をはっきり感じやすい', null, '成熟日数の中央値は125日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '個性が強く好みが分かれやすい', 'ゴレックはインドネシアのマンゴーで，小ぶりの果実です．糖度が高めで酸味はやや強め．果皮色は黄橙．肉質は繊維をはっきり感じやすい．個性が強く好みが分かれやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-022）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-022.pdf', true),
  ('ゴウベイア', 'Gouveia', 'gouveia', 'アメリカ（ハワイ）', 'アメリカ（ハワイ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-023として整理されています．', '367g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度15.5度，酸度0.15%です．', null, null, '成熟日数の中央値は121日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'ゴウベイアはアメリカ（ハワイ）のマンゴーで，中玉の果実です．糖度は中程度で酸味は中程度．果皮色は黄と赤．食味のまとまりがあり試しやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-023）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-023.pdf', true),
  ('ハッチャー', 'Hatcher', 'hatcher', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-028として整理されています．', '628g（JIRCAS調査平均）．大玉寄り．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度15.5度，酸度0.18%です．', 'みずみずしい肉質', 'マンゴーらしい香り', '成熟日数の中央値は156日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'ハッチャーはアメリカ（フロリダ）のマンゴーで，大玉寄りの果実です．糖度は中程度で酸味は中程度．果皮色は黄と赤．肉質はみずみずしい肉質．マンゴーらしい香り．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-028）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-028.pdf', true),
  ('ハドソン', 'Hodson', 'hodson', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-029として整理されています．', '436g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度16.3度，酸度0.18%です．', 'みずみずしい肉質', null, '成熟日数の中央値は133日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'ハドソンはアメリカ（フロリダ）のマンゴーで，中玉の果実です．糖度は中程度で酸味は中程度．果皮色は橙と赤．肉質はみずみずしい肉質．食味のまとまりがあり試しやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-029）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-029.pdf', true),
  ('アーウィン', 'Irwin', 'irwin', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-030として整理されています．', '470g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度15.0度，酸度0.16%です．', null, '華やかな香り', '成熟日数の中央値は132日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'アーウィンはアメリカ（フロリダ）のマンゴーで，中玉の果実です．糖度は中程度で酸味は中程度．果皮色は橙と赤．華やかな香り．食味のまとまりがあり試しやすい．国内でよく知られる代表的な赤色系品種として扱いやすい情報です．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-030）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-030.pdf', true),
  ('ジュエル', 'Jewel', 'jewel', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-033として整理されています．', '464g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度17.8度，酸度0.15%です．', null, '香りは穏やか', '成熟日数の中央値は136日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '甘味主体で受け入れられやすい', 'ジュエルはアメリカ（フロリダ）のマンゴーで，中玉の果実です．糖度は中程度で酸味は中程度．果皮色は橙と赤．香りは穏やか．甘味主体で受け入れられやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-033）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-033.pdf', true),
  ('ジュビリー', 'Jubilee', 'jubilee', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-034として整理されています．', '478g（JIRCAS調査平均）．中玉．', '甘さは控えめ，酸味は中程度．JIRCAS調査値は糖度12.9度，酸度0.19%です．', 'なめらかで口当たりがよいタイプ', null, '成熟日数の中央値は142日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'ジュビリーはアメリカ（フロリダ）のマンゴーで，中玉の果実です．甘さは控えめで酸味は中程度．果皮色は赤．肉質はなめらかで口当たりがよいタイプ．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-034）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-034.pdf', true),
  ('ケンジントン', 'Kensington', 'kensington', 'オーストラリア', 'オーストラリアに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-037として整理されています．', '385g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度16.2度，酸度0.18%です．', 'なめらかで口当たりがよいタイプ', 'マンゴーらしい香り', '成熟日数の中央値は129日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'ケンジントンはオーストラリアのマンゴーで，中玉の果実です．糖度は中程度で酸味は中程度．果皮色は黄と橙．肉質はなめらかで口当たりがよいタイプ．マンゴーらしい香り．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-037）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-037.pdf', true),
  ('キンコウ', 'Kinkou', 'kinkou', '台湾', '台湾に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-040として整理されています．', '759g（JIRCAS調査平均）．大玉寄り．', '糖度は中程度，酸味は穏やか．JIRCAS調査値は糖度17.0度，酸度0.11%です．', null, null, '成熟日数の中央値は121日（JIRCAS石垣調査）．', '収穫タイミングと品質管理に注意', 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'キンコウは台湾のマンゴーで，大玉寄りの果実です．糖度は中程度で酸味は穏やか．果皮色は黄と橙．収穫タイミングと品質管理に注意．食味のまとまりがあり試しやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-040）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-040.pdf', true),
  ('コウリュウ', 'Kouryu', 'kouryu', '台湾', '台湾に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-041として整理されています．', '686g（JIRCAS調査平均）．大玉寄り．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度15.5度，酸度0.18%です．', 'なめらかで口当たりがよいタイプ', 'マンゴーらしい香り', '成熟日数の中央値は111日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'コウリュウは台湾のマンゴーで，大玉寄りの果実です．糖度は中程度で酸味は中程度．果皮色は黄．肉質はなめらかで口当たりがよいタイプ．マンゴーらしい香り．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-041）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-041.pdf', true),
  ('キヨ サワイ', 'Kyo Savoy', 'kyo-savoy', 'タイ', 'タイに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-042として整理されています．', '392g（JIRCAS調査平均）．中玉．', '糖度は高め，酸味は中程度．JIRCAS調査値は糖度18.4度，酸度0.15%です．', null, null, '成熟日数の中央値は137日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '個性が強く好みが分かれやすい', 'キヨ サワイはタイのマンゴーで，中玉の果実です．糖度が高めで酸味は中程度．果皮色は黄緑．個性が強く好みが分かれやすい．完熟果だけでなく未熟果利用の文脈でも比較したい品種です．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-042）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-042.pdf', true),
  ('ランセティーラ', 'Lancetilla', 'lancetilla', 'ホンジュラス', 'ホンジュラスに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-043として整理されています．', '1095g（JIRCAS調査平均）．かなり大玉の部類．', '甘さは控えめ，酸味は強め．JIRCAS調査値は糖度14.9度，酸度0.61%です．', 'なめらかで口当たりがよいタイプ', '香りは穏やか', '成熟日数の中央値は144日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'ランセティーラはホンジュラスのマンゴーで，かなり大玉の部類の果実です．甘さは控えめで酸味は強め．果皮色は黄と橙．肉質はなめらかで口当たりがよいタイプ．香りは穏やか．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-043）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-043.pdf', true),
  ('リリー', 'Lily', 'lily', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-044として整理されています．', '564g（JIRCAS調査平均）．大玉寄り．', '甘さは控えめ，酸味は中程度．JIRCAS調査値は糖度14.6度，酸度0.20%です．', 'ややしっかりした肉質', null, '成熟日数の中央値は137日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'リリーはアメリカ（フロリダ）のマンゴーで，大玉寄りの果実です．甘さは控えめで酸味は中程度．果皮色は橙と紫．肉質はややしっかりした肉質．食味のまとまりがあり試しやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-044）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-044.pdf', true),
  ('リペンス', 'Lippens', 'lippens', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-045として整理されています．', '516g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度15.5度，酸度0.16%です．', 'なめらかで口当たりがよいタイプ', null, '成熟日数の中央値は145日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'リペンスはアメリカ（フロリダ）のマンゴーで，中玉の果実です．糖度は中程度で酸味は中程度．果皮色は橙．肉質はなめらかで口当たりがよいタイプ．食味のまとまりがあり試しやすい．沖縄では夏小紅の名前でも知られます．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-045）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-045.pdf', true),
  ('マダム フランシス', 'Madame Francis', 'madame-francis', 'ハイチ', 'ハイチに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-046として整理されています．', '663g（JIRCAS調査平均）．大玉寄り．', '糖度は高め，酸味は中程度．JIRCAS調査値は糖度19.3度，酸度0.20%です．', 'ややざらつきを感じる肉質', 'マンゴーらしい香り', '成熟日数の中央値は151日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '個性が強く好みが分かれやすい', 'マダム フランシスはハイチのマンゴーで，大玉寄りの果実です．糖度が高めで酸味は中程度．果皮色は黄．肉質はややざらつきを感じる肉質．マンゴーらしい香り．個性が強く好みが分かれやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-046）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-046.pdf', true),
  ('マグシャミン', 'Magshamim', 'magshamim', 'イスラエル', 'イスラエルに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-047として整理されています．', '414g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味はやや強め．JIRCAS調査値は糖度16.9度，酸度0.25%です．', 'なめらかで口当たりがよいタイプ', null, '成熟日数の中央値は130日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'マグシャミンはイスラエルのマンゴーで，中玉の果実です．糖度は中程度で酸味はやや強め．果皮色は橙と紫．肉質はなめらかで口当たりがよいタイプ．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-047）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-047.pdf', true),
  ('マリカ', 'Mallika', 'mallika', 'インド', 'インドに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-049として整理されています．', '547g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度15.6度，酸度0.24%です．', 'ややざらつきを感じる肉質', '個性的な香り', '成熟日数の中央値は123日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '個性が強く好みが分かれやすい', 'マリカはインドのマンゴーで，中玉の果実です．糖度は中程度で酸味は中程度．果皮色は黄．肉質はややざらつきを感じる肉質．個性的な香り．個性が強く好みが分かれやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-049）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-049.pdf', true),
  ('マニリタ', 'Manilita', 'manilita', 'メキシコ', 'メキシコに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-050として整理されています．', '281g（JIRCAS調査平均）．小ぶり．', '糖度は中程度，酸味はやや強め．JIRCAS調査値は糖度17.8度，酸度0.29%です．', null, 'マンゴーらしい香り', '成熟日数の中央値は115日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'マニリタはメキシコのマンゴーで，小ぶりの果実です．糖度は中程度で酸味はやや強め．果皮色は黄と橙．マンゴーらしい香り．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-050）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-050.pdf', true),
  ('マンザニーロ', 'Manzanillo', 'manzanillo', 'メキシコ', 'メキシコに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-051として整理されています．', '662g（JIRCAS調査平均）．大玉寄り．', '糖度は高め，酸味は強め．JIRCAS調査値は糖度18.5度，酸度0.42%です．', null, null, '成熟日数の中央値は154日（JIRCAS石垣調査）．', 'JIRCASで着果性の記録があり観察向き', 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'マンザニーロはメキシコのマンゴーで，大玉寄りの果実です．糖度が高めで酸味は強め．果皮色は橙と赤．JIRCASで着果性の記録があり観察向き．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-051）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-051.pdf', true),
  ('マプレフ', 'Mapulehu', 'mapulehu', '不明', '不明に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-052として整理されています．', '495g（JIRCAS調査平均）．中玉．', '甘さは控えめ，酸味は中程度．JIRCAS調査値は糖度14.8度，酸度0.22%です．', null, '個性的な香り', '成熟日数の中央値は135日（JIRCAS石垣調査）．', 'JIRCASで着果性の記録があり観察向き', 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '個性が強く好みが分かれやすい', 'マプレフは不明のマンゴーで，中玉の果実です．甘さは控えめで酸味は中程度．果皮色は黄と橙．個性的な香り．JIRCASで着果性の記録があり観察向き．個性が強く好みが分かれやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-052）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-052.pdf', true),
  ('マイヤー', 'Mayer', 'mayer', '不明', '不明に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-053として整理されています．', '410g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度16.0度，酸度0.15%です．', 'なめらかで口当たりがよいタイプ', null, '成熟日数の中央値は125日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '個性が強く好みが分かれやすい', 'マイヤーは不明のマンゴーで，中玉の果実です．糖度は中程度で酸味は中程度．果皮色は橙と赤．肉質はなめらかで口当たりがよいタイプ．個性が強く好みが分かれやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-053）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-053.pdf', true),
  ('モミーケイ', 'Momi-K', 'momi-k', 'アメリカ（ハワイ）', 'アメリカ（ハワイ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-054として整理されています．', '227g（JIRCAS調査平均）．小ぶり．', '甘さは控えめ，酸味は中程度．JIRCAS調査値は糖度14.1度，酸度0.22%です．', 'なめらかで口当たりがよいタイプ', null, '成熟日数の中央値は111日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'モミーケイはアメリカ（ハワイ）のマンゴーで，小ぶりの果実です．甘さは控えめで酸味は中程度．果皮色は橙と赤．肉質はなめらかで口当たりがよいタイプ．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-054）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-054.pdf', true),
  ('ナム ドク マイ', 'Nam Doc Mai', 'nam-doc-mai', 'タイ', 'タイに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-055として整理されています．', '440g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は穏やか．JIRCAS調査値は糖度15.9度，酸度0.09%です．', 'なめらかで口当たりがよいタイプ', 'マンゴーらしい香り', '成熟日数の中央値は126日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'ナム ドク マイはタイのマンゴーで，中玉の果実です．糖度は中程度で酸味は穏やか．果皮色は黄．肉質はなめらかで口当たりがよいタイプ．マンゴーらしい香り．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-055）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-055.pdf', true),
  ('ナム ドク マイ ニゴウ', 'Nam Doc Mai #2', 'nam-doc-mai-2', '不明', '不明に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-056として整理されています．', '518g（JIRCAS調査平均）．中玉．', '甘さは控えめ，酸味は穏やか．JIRCAS調査値は糖度14.1度，酸度0.13%です．', 'みずみずしい肉質', '個性的な香り', '成熟日数の中央値は137日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '個性が強く好みが分かれやすい', 'ナム ドク マイ ニゴウは不明のマンゴーで，中玉の果実です．甘さは控えめで酸味は穏やか．果皮色は黄．肉質はみずみずしい肉質．個性的な香り．個性が強く好みが分かれやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-056）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-056.pdf', true),
  ('ナム ドク マイ ヨンゴウ', 'Nam Doc Mai #4', 'nam-doc-mai-4', 'タイ', 'タイに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-057として整理されています．', '482g（JIRCAS調査平均）．中玉．', '糖度は高め，酸味は穏やか．JIRCAS調査値は糖度19.3度，酸度0.12%です．', 'なめらかで口当たりがよいタイプ', 'マンゴーらしい香り', '成熟日数の中央値は135日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '甘味主体で受け入れられやすい', 'ナム ドク マイ ヨンゴウはタイのマンゴーで，中玉の果実です．糖度が高めで酸味は穏やか．果皮色は黄．肉質はなめらかで口当たりがよいタイプ．マンゴーらしい香り．甘味主体で受け入れられやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-057）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-057.pdf', true),
  ('ナオミ', 'Naomi', 'naomi', 'イスラエル', 'イスラエルに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-058として整理されています．', '614g（JIRCAS調査平均）．大玉寄り．', '糖度は中程度，酸味は強め．JIRCAS調査値は糖度17.3度，酸度0.35%です．', null, null, '成熟日数の中央値は147日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'ナオミはイスラエルのマンゴーで，大玉寄りの果実です．糖度は中程度で酸味は強め．果皮色は赤．食味のまとまりがあり試しやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-058）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-058.pdf', true),
  ('ニーラムレイト', 'Neelumlate', 'neelumlate', 'インド', 'インドに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-059として整理されています．', '344g（JIRCAS調査平均）．小ぶり．', '糖度は中程度，酸味は強め．JIRCAS調査値は糖度16.0度，酸度0.43%です．', '繊維をはっきり感じやすい', '香りは強め', '成熟日数の中央値は146日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'ニーラムレイトはインドのマンゴーで，小ぶりの果実です．糖度は中程度で酸味は強め．果皮色は黄と橙．肉質は繊維をはっきり感じやすい．香りは強め．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-059）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-059.pdf', true),
  ('オスティーン', 'Osteen', 'osteen', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-062として整理されています．', '662g（JIRCAS調査平均）．大玉寄り．', '糖度は中程度，酸味はやや強め．JIRCAS調査値は糖度16.8度，酸度0.25%です．', '繊維は少なめ', 'マンゴーらしい香り', '成熟日数の中央値は134日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'オスティーンはアメリカ（フロリダ）のマンゴーで，大玉寄りの果実です．糖度は中程度で酸味はやや強め．果皮色は橙と赤．肉質は繊維は少なめ．マンゴーらしい香り．食味のまとまりがあり試しやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-062）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-062.pdf', true),
  ('パーマー', 'Palmer', 'palmer', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-063として整理されています．', '625g（JIRCAS調査平均）．大玉寄り．', '甘さは控えめ，酸味はやや強め．JIRCAS調査値は糖度14.7度，酸度0.25%です．', 'ややしっかりした肉質', '香りが良い', '成熟日数の中央値は145日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'パーマーはアメリカ（フロリダ）のマンゴーで，大玉寄りの果実です．甘さは控えめで酸味はやや強め．果皮色は橙と赤．肉質はややしっかりした肉質．香りが良い．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-063）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-063.pdf', true),
  ('ピーバ', 'Piva', 'piva', '不明', '不明に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-065として整理されています．', '519g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は強め．JIRCAS調査値は糖度15.4度，酸度0.37%です．', 'ややしっかりした肉質', null, '成熟日数の中央値は128日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'ピーバは不明のマンゴーで，中玉の果実です．糖度は中程度で酸味は強め．果皮色は赤．肉質はややしっかりした肉質．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-065）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-065.pdf', true),
  ('アールトゥーイートゥー', 'R2E2', 'r2e2', 'オーストラリア', 'オーストラリアに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-067として整理されています．', '595g（JIRCAS調査平均）．大玉寄り．', '甘さは控えめ，酸味は中程度．JIRCAS調査値は糖度12.1度，酸度0.15%です．', null, '個性的な香り', '成熟日数の中央値は135日（JIRCAS石垣調査）．', 'JIRCASで着果性の記録があり観察向き', 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '個性が強く好みが分かれやすい', 'アールトゥーイートゥーはオーストラリアのマンゴーで，大玉寄りの果実です．甘さは控えめで酸味は中程度．果皮色は橙．個性的な香り．JIRCASで着果性の記録があり観察向き．個性が強く好みが分かれやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-067）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-067.pdf', true),
  ('ラッド', 'Rad', 'rad', 'タイ', 'タイに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-068として整理されています．', '423g（JIRCAS調査平均）．中玉．', '糖度は高め，酸味は中程度．JIRCAS調査値は糖度19.6度，酸度0.19%です．', null, 'マンゴーらしい香り', '成熟日数の中央値は131日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '甘味主体で受け入れられやすい', 'ラッドはタイのマンゴーで，中玉の果実です．糖度が高めで酸味は中程度．果皮色は黄．マンゴーらしい香り．甘味主体で受け入れられやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-068）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-068.pdf', true),
  ('ラポザ', 'Rapoza', 'rapoza', 'アメリカ（ハワイ）', 'アメリカ（ハワイ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-069として整理されています．', '535g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度15.3度，酸度0.17%です．', 'なめらかで口当たりがよいタイプ', null, '成熟日数の中央値は147日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'ラポザはアメリカ（ハワイ）のマンゴーで，中玉の果実です．糖度は中程度で酸味は中程度．果皮色は赤．肉質はなめらかで口当たりがよいタイプ．食味のまとまりがあり試しやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-069）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-069.pdf', true),
  ('ルビー', 'Ruby', 'ruby', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-070として整理されています．', '312g（JIRCAS調査平均）．小ぶり．', '糖度は高め，酸味は中程度．JIRCAS調査値は糖度18.6度，酸度0.21%です．', null, null, '成熟日数の中央値は133日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'ルビーはアメリカ（フロリダ）のマンゴーで，小ぶりの果実です．糖度が高めで酸味は中程度．果皮色は赤．食味のまとまりがあり試しやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-070）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-070.pdf', true),
  ('センセーション', 'Sensation', 'sensation', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-071として整理されています．', '333g（JIRCAS調査平均）．小ぶり．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度16.7度，酸度0.16%です．', null, 'マンゴーらしい香り', '成熟日数の中央値は131日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'センセーションはアメリカ（フロリダ）のマンゴーで，小ぶりの果実です．糖度は中程度で酸味は中程度．果皮色は黄と赤．マンゴーらしい香り．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-071）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-071.pdf', true),
  ('スピリット オブ セブンティシックス', 'Spirit of ''76', 'spirit-of-76', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-074として整理されています．', '451g（JIRCAS調査平均）．中玉．', '糖度は高め，酸味は中程度．JIRCAS調査値は糖度19.3度，酸度0.21%です．', null, null, '成熟日数の中央値は140日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'スピリット オブ セブンティシックスはアメリカ（フロリダ）のマンゴーで，中玉の果実です．糖度が高めで酸味は中程度．果皮色は橙．食味のまとまりがあり試しやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-074）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-074.pdf', true),
  ('スプリングフェルズ', 'Springfels', 'springfels', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-075として整理されています．', '735g（JIRCAS調査平均）．大玉寄り．', '糖度は中程度，酸味は強め．JIRCAS調査値は糖度17.2度，酸度0.68%です．', '繊維は少なめ', null, '成熟日数の中央値は134日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'スプリングフェルズはアメリカ（フロリダ）のマンゴーで，大玉寄りの果実です．糖度は中程度で酸味は強め．果皮色は黄と橙．肉質は繊維は少なめ．食味のまとまりがあり試しやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-075）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-075.pdf', true),
  ('タハール', 'Tahar', 'tahar', 'イスラエル', 'イスラエルに由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-076として整理されています．', '405g（JIRCAS調査平均）．中玉．', '甘さは控えめ，酸味は中程度．JIRCAS調査値は糖度14.2度，酸度0.19%です．', '繊維は少なめ', null, '成熟日数の中央値は126日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'タハールはイスラエルのマンゴーで，中玉の果実です．甘さは控えめで酸味は中程度．果皮色は赤．肉質は繊維は少なめ．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-076）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-076.pdf', true),
  ('タイノウ イチゴウ', 'Tainoung-1', 'tainoung-1', '台湾', '台湾に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-077として整理されています．', '301g（JIRCAS調査平均）．小ぶり．', '糖度は非常に高い，酸味は中程度．JIRCAS調査値は糖度20.2度，酸度0.17%です．', null, '個性的な香り', '成熟日数の中央値は131日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '個性が強く好みが分かれやすい', 'タイノウ イチゴウは台湾のマンゴーで，小ぶりの果実です．糖度が非常に高く酸味は中程度．果皮色は橙と赤．個性的な香り．個性が強く好みが分かれやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-077）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-077.pdf', true),
  ('トミー アトキンス', 'Tommy Atkins', 'tommy-atkins', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-079として整理されています．', '597g（JIRCAS調査平均）．大玉寄り．', '糖度は中程度，酸味は穏やか．JIRCAS調査値は糖度15.2度，酸度0.10%です．', 'ややしっかりした肉質', '個性的な香り', '成熟日数の中央値は135日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '個性が強く好みが分かれやすい', 'トミー アトキンスはアメリカ（フロリダ）のマンゴーで，大玉寄りの果実です．糖度は中程度で酸味は穏やか．果皮色は黄と赤．肉質はややしっかりした肉質．個性的な香り．個性が強く好みが分かれやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-079）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-079.pdf', true),
  ('トルベット', 'Torbet', 'torbet', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-080として整理されています．', '417g（JIRCAS調査平均）．中玉．', '糖度は中程度，酸味は中程度．JIRCAS調査値は糖度16.6度，酸度0.22%です．', '弾力のある肉質', null, '成熟日数の中央値は121日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '個性が強く好みが分かれやすい', 'トルベットはアメリカ（フロリダ）のマンゴーで，中玉の果実です．糖度は中程度で酸味は中程度．果皮色は橙と赤．肉質は弾力のある肉質．個性が強く好みが分かれやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-080）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-080.pdf', true),
  ('ターペンタイン', 'Turpentine', 'turpentine', '中南米（詳細不明）', '中南米（詳細不明）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-081として整理されています．', '175g（JIRCAS調査平均）．小ぶり．', '甘さは控えめ，酸味は穏やか．JIRCAS調査値は糖度14.1度，酸度0.13%です．', null, null, '成熟日数の中央値は128日（JIRCAS石垣調査）．', 'JIRCASで着果性の記録があり観察向き', 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'ターペンタインは中南米（詳細不明）のマンゴーで，小ぶりの果実です．甘さは控えめで酸味は穏やか．果皮色は黄．JIRCASで着果性の記録があり観察向き．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-081）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-081.pdf', true),
  ('バレンシア プライド', 'Valencia Pride', 'valencia-pride', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-082として整理されています．', '565g（JIRCAS調査平均）．大玉寄り．', '糖度は中程度，酸味はやや強め．JIRCAS調査値は糖度16.8度，酸度0.30%です．', null, null, '成熟日数の中央値は144日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '食味のまとまりがあり試しやすい', 'バレンシア プライドはアメリカ（フロリダ）のマンゴーで，大玉寄りの果実です．糖度は中程度で酸味はやや強め．果皮色は黄と赤．食味のまとまりがあり試しやすい．沖縄ではてぃららの名前でも知られます．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-082）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-082.pdf', true),
  ('バン ダイク', 'Van Dyke', 'van-dyke', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-084として整理されています．', '407g（JIRCAS調査平均）．中玉．', '糖度は高め，酸味は中程度．JIRCAS調査値は糖度18.1度，酸度0.24%です．', null, 'マンゴーらしい香り', '成熟日数の中央値は133日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '甘味主体で受け入れられやすい', 'バン ダイクはアメリカ（フロリダ）のマンゴーで，中玉の果実です．糖度が高めで酸味は中程度．果皮色は橙と赤．マンゴーらしい香り．甘味主体で受け入れられやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-084）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-084.pdf', true),
  ('ホワイト', 'White', 'white', '不明', '不明に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-085として整理されています．', '464g（JIRCAS調査平均）．中玉．', '糖度は高め，酸味は穏やか．JIRCAS調査値は糖度18.8度，酸度0.12%です．', null, null, '成熟日数の中央値は143日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '甘味主体で受け入れられやすい', 'ホワイトは不明のマンゴーで，中玉の果実です．糖度が高めで酸味は穏やか．果皮色は黄．甘味主体で受け入れられやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-085）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-085.pdf', true),
  ('ホワイト ピリー', 'White Pirie', 'white-pirie', 'アメリカ（ハワイ）', 'アメリカ（ハワイ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-086として整理されています．', '289g（JIRCAS調査平均）．小ぶり．', '糖度は高め，酸味は中程度．JIRCAS調査値は糖度18.9度，酸度0.22%です．', null, '華やかな香り', '成熟日数の中央値は141日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', '甘味主体で受け入れられやすい', 'ホワイト ピリーはアメリカ（ハワイ）のマンゴーで，小ぶりの果実です．糖度が高めで酸味は中程度．果皮色は黄橙．華やかな香り．甘味主体で受け入れられやすい．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-086）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-086.pdf', true),
  ('ジレイト', 'Zillate', 'zillate', 'アメリカ（フロリダ）', 'アメリカ（フロリダ）に由来するマンゴー品種．JIRCASマンゴー遺伝資源データベースではJTMG-088として整理されています．', '652g（JIRCAS調査平均）．大玉寄り．', '糖度は中程度，酸味は強め．JIRCAS調査値は糖度17.9度，酸度0.35%です．', null, null, '成熟日数の中央値は146日（JIRCAS石垣調査）．', null, 'JIRCAS熱帯・島嶼研究拠点（石垣）で調査対象になっており，沖縄での比較検討に使いやすい品種情報です．', '鉢栽培調査のデータを含むため，鉢管理での比較候補になります．', null, 'ジレイトはアメリカ（フロリダ）のマンゴーで，大玉寄りの果実です．糖度は中程度で酸味は強め．果皮色は橙と紫．', '出典: JIRCASマンゴー遺伝資源サイト（JTMG-088）．データベース: https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり: https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報シートPDF: https://www.jircas.go.jp/themes/custom/mango/data/pdf/JTMG-088.pdf', true)
),
normalized as (
  select
    source.*,
    'JIRCAS果実重: ' || source.fruit_size as jircas_fruit_size,
    'JIRCAS品質: ' || source.taste as jircas_taste,
    'JIRCAS成熟日数: ' || source.harvest_season as jircas_harvest,
    concat_ws(
      ' ',
      'JIRCAS石垣調査では，' || source.fruit_size,
      source.taste,
      source.harvest_season
    ) as jircas_description_note
  from source
)
update public.cultivars c
set
  fruit_size = case
    when nullif(c.fruit_size, '') is null then normalized.jircas_fruit_size
    when c.fruit_size like '%JIRCAS果実重:%' or c.fruit_size like '%JIRCAS調査平均%' then c.fruit_size
    else concat_ws(E'\n', c.fruit_size, normalized.jircas_fruit_size)
  end,
  taste = case
    when nullif(c.taste, '') is null then normalized.jircas_taste
    when c.taste like '%JIRCAS品質:%' or c.taste like '%JIRCAS調査値%' then c.taste
    else concat_ws(E'\n', c.taste, normalized.jircas_taste)
  end,
  harvest_season = case
    when nullif(c.harvest_season, '') is null then normalized.jircas_harvest
    when c.harvest_season like '%JIRCAS成熟日数:%' or c.harvest_season like '%成熟日数の中央値%' then c.harvest_season
    else concat_ws(E'\n', c.harvest_season, normalized.jircas_harvest)
  end,
  description = case
    when nullif(c.description, '') is null then normalized.jircas_description_note
    when c.description like '%JIRCAS石垣調査では%' then c.description
    else concat_ws(E'\n', c.description, normalized.jircas_description_note)
  end,
  public_notes = case
    when coalesce(c.public_notes, '') like '%JIRCASマンゴー遺伝資源サイト%' then c.public_notes
    else concat_ws(
      E'\n',
      nullif(c.public_notes, ''),
      '出典: JIRCASマンゴー遺伝資源サイト https://www.jircas.go.jp/ja/database/mango/mango-database / 品種早わかり https://www.jircas.go.jp/ja/database/mango/catalogue / 品質特性情報 https://www.jircas.go.jp/ja/database/mango/quality-characteristic'
    )
  end,
  updated_at = now()
from normalized
join mango on true
where c.fruit_id = mango.id
  and c.slug = normalized.slug;

select
  count(*) as mango_cultivars_with_jircas_numbers
from public.cultivars c
join public.fruits f on f.id = c.fruit_id
where f.slug = 'mango'
  and (
    c.taste like '%JIRCAS品質:%'
    or c.taste like '%JIRCAS調査値%'
  );

commit;
